# Generated by Django 2.1.7 on 2019-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190224_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='mnieber', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
