# Generated by Django 2.1.7 on 2019-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recent_move_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='recent_move_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
