version: "3.7"

services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: linsci_backend
    ports:
      - "8000:8000"
    env_file:
      - .env/backend.env
      - .env/postgres.env
    volumes:
      - type: volume
        source: backend_site_packages
        target: /usr/local/lib/python3.8/site-packages
    command: sleep 10000000
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: linsci_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env/frontend.env
    command: sleep 10000000
  db:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/postgres.env
    ports:
      - "5432:5432"
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - "4873:4873"

volumes:
  backend_site_packages:
  postgres_data:
