version: "3.7"

services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: linsci_backend
    ports:
      - "8000:8000"
    env_file:
      - .env/backend.env
      - .env/postgres.env

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: linsci_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env/frontend.env

  db:
    image: postgres:11.5
    env_file:
      - ./.env/postgres.env
    ports:
      - "5432:5432"
