version: "3.7"

services:
  backend_build:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: linsci_backend
    entrypoint: []
    command: echo

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    image: linsci_backend_dev

    volumes:
      # map the src directory to opt/app-root/src
      - ./backend:/opt/linsci/src
      # Preserve the following directories written by the docker container
      # Note: first run `sudo python dev/configure.py` to create /srv/linsci
      - /opt/linsci/pypi:/opt/linsci/pypi
      - /opt/linsci/static:/opt/linsci/static
      - /opt/linsci/dumps:/opt/linsci/dumps
      - /opt/linsci/log:/opt/linsci/log
      - /opt/linsci/.pytest_report:/opt/linsci/.pytest_report
      - /opt/linsci/.ipython:/opt/linsci/.ipython
      - /opt/linsci/.bashrc:/opt/linsci/.bashrc
      - /opt/linsci/.config:/opt/linsci/.config
      - $HOME/.config/pudb:/root/.config/pudb

  frontend_build:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: linsci_frontend
    entrypoint: []
    command: echo

  frontend:
    depends_on:
      - frontend_build
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    image: linsci_frontend_dev
    volumes:
      # map the src directory to opt/app-root/src
      - ./frontend:/opt/linsci/src
      - /home/maarten/projects/aspiration/src:/opt/linsci/npm/aspiration
      - /home/maarten/projects/react-form-state-context/src:/opt/linsci/npm/react-form-state-context
      - /home/maarten/projects/react-default-props-context/src:/opt/linsci/npm/react-default-props-context
      - /home/maarten/projects/facility/src:/opt/linsci/npm/facility
      - /home/maarten/projects/facility-mobx/src:/opt/linsci/npm/facility-mobx
      # Preserve the following directories written by the docker container
      # Note: first run `sudo python dev/configure.py` to create /srv/linsci
      - /opt/linsci/frontend/fish_history:/root/.local/share/fish/fish_history

  # verdaccio:
  #   image: verdaccio/verdaccio
  #   ports:
  #     - "4873:4873"
  #   volumes:
  #     - verdaccio_data:/verdaccio
# volumes:
#   verdaccio_data:
