FROM python:3.8-alpine

ENV PYTHONUNBUFFERED 1

RUN apk update \
    # psycopg2 dependencies
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add postgresql-dev \
    # Pillow dependencies
    && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \
    # CFFI dependencies
    && apk add libffi-dev py-cffi \
    # Translations dependencies
    && apk add gettext \
    # graph_models dependencies
    && apk add graphviz \
    # https://docs.djangoproject.com/en/dev/ref/django-admin/#dbshell
    && apk add postgresql-client git

RUN pip install --upgrade pip && pip install pip-tools

RUN apk add make mlocate nano fish curl

RUN mkdir -p /opt/linsci
WORKDIR /opt/linsci/src

CMD sleep infinity