// flow-typed signature: a03e20c144b8d94f1d2c667818f19070
// flow-typed version: <<STUB>>/extend-tape_v^1.2.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extend-tape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extend-tape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extend-tape/dist/index' {
  declare module.exports: any;
}

declare module 'extend-tape/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extend-tape/dist/index.js' {
  declare module.exports: $Exports<'extend-tape/dist/index'>;
}
declare module 'extend-tape/tests/test.js' {
  declare module.exports: $Exports<'extend-tape/tests/test'>;
}
