// flow-typed signature: d839aaab9ea367a0a1e20116edd85d88
// flow-typed version: <<STUB>>/js-video-url-parser_v^0.4.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-video-url-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-video-url-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-video-url-parser/dist/jsVideoUrlParser' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/dist/jsVideoUrlParser.min' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/base' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/index' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/canalplus' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/coub' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/dailymotion' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/soundcloud' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/teachertube' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/twitch' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/vimeo' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/wistia' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/youku' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/provider/youtube' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/testUrls' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/urlParser' {
  declare module.exports: any;
}

declare module 'js-video-url-parser/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-video-url-parser/dist/jsVideoUrlParser.js' {
  declare module.exports: $Exports<'js-video-url-parser/dist/jsVideoUrlParser'>;
}
declare module 'js-video-url-parser/dist/jsVideoUrlParser.min.js' {
  declare module.exports: $Exports<'js-video-url-parser/dist/jsVideoUrlParser.min'>;
}
declare module 'js-video-url-parser/lib/base.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/base'>;
}
declare module 'js-video-url-parser/lib/index.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/index'>;
}
declare module 'js-video-url-parser/lib/provider/canalplus.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/canalplus'>;
}
declare module 'js-video-url-parser/lib/provider/coub.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/coub'>;
}
declare module 'js-video-url-parser/lib/provider/dailymotion.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/dailymotion'>;
}
declare module 'js-video-url-parser/lib/provider/soundcloud.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/soundcloud'>;
}
declare module 'js-video-url-parser/lib/provider/teachertube.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/teachertube'>;
}
declare module 'js-video-url-parser/lib/provider/twitch.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/twitch'>;
}
declare module 'js-video-url-parser/lib/provider/vimeo.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/vimeo'>;
}
declare module 'js-video-url-parser/lib/provider/wistia.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/wistia'>;
}
declare module 'js-video-url-parser/lib/provider/youku.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/youku'>;
}
declare module 'js-video-url-parser/lib/provider/youtube.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/provider/youtube'>;
}
declare module 'js-video-url-parser/lib/testUrls.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/testUrls'>;
}
declare module 'js-video-url-parser/lib/urlParser.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/urlParser'>;
}
declare module 'js-video-url-parser/lib/util.js' {
  declare module.exports: $Exports<'js-video-url-parser/lib/util'>;
}
