// flow-typed signature: fbbf7580c60f85348234573a37ef833b
// flow-typed version: <<STUB>>/micro-signals_v^2.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-signals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-signals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-signals/lib/caches' {
  declare module.exports: any;
}

declare module 'micro-signals/lib/extended-signal' {
  declare module.exports: any;
}

declare module 'micro-signals/lib/index' {
  declare module.exports: any;
}

declare module 'micro-signals/lib/interfaces' {
  declare module.exports: any;
}

declare module 'micro-signals/lib/signal' {
  declare module.exports: any;
}

declare module 'micro-signals/lib/tag-map' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-signals/lib/caches.js' {
  declare module.exports: $Exports<'micro-signals/lib/caches'>;
}
declare module 'micro-signals/lib/extended-signal.js' {
  declare module.exports: $Exports<'micro-signals/lib/extended-signal'>;
}
declare module 'micro-signals/lib/index.js' {
  declare module.exports: $Exports<'micro-signals/lib/index'>;
}
declare module 'micro-signals/lib/interfaces.js' {
  declare module.exports: $Exports<'micro-signals/lib/interfaces'>;
}
declare module 'micro-signals/lib/signal.js' {
  declare module.exports: $Exports<'micro-signals/lib/signal'>;
}
declare module 'micro-signals/lib/tag-map.js' {
  declare module.exports: $Exports<'micro-signals/lib/tag-map'>;
}
