// flow-typed signature: 9acc7f3d8355438f52e49c5a4cb319e9
// flow-typed version: <<STUB>>/mobx-react_v^6.1.4/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react/dist/mobx-react' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobx-react.module' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobx-react.rn.module' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobx-react.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react/dist/mobx-react.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobx-react'>;
}
declare module 'mobx-react/dist/mobx-react.module.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobx-react.module'>;
}
declare module 'mobx-react/dist/mobx-react.rn.module.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobx-react.rn.module'>;
}
declare module 'mobx-react/dist/mobx-react.umd.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobx-react.umd'>;
}
