// flow-typed signature: 1b435d8afec11d6aa2ae94ab6077037e
// flow-typed version: <<STUB>>/rambda_v5.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rambda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rambda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rambda/dist/rambda.esm' {
  declare module.exports: any;
}

declare module 'rambda/dist/rambda' {
  declare module.exports: any;
}

declare module 'rambda/dist/rambda.umd' {
  declare module.exports: any;
}

declare module 'rambda/src/_build.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/_typings.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/add' {
  declare module.exports: any;
}

declare module 'rambda/src/add.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/adjust' {
  declare module.exports: any;
}

declare module 'rambda/src/adjust.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/all' {
  declare module.exports: any;
}

declare module 'rambda/src/all.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/allPass' {
  declare module.exports: any;
}

declare module 'rambda/src/allPass.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/always' {
  declare module.exports: any;
}

declare module 'rambda/src/always.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/and' {
  declare module.exports: any;
}

declare module 'rambda/src/and.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/any' {
  declare module.exports: any;
}

declare module 'rambda/src/any.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/anyPass' {
  declare module.exports: any;
}

declare module 'rambda/src/anyPass.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/append' {
  declare module.exports: any;
}

declare module 'rambda/src/append.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/applySpec' {
  declare module.exports: any;
}

declare module 'rambda/src/applySpec.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/assoc' {
  declare module.exports: any;
}

declare module 'rambda/src/assoc.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/assocPath' {
  declare module.exports: any;
}

declare module 'rambda/src/assocPath.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/both' {
  declare module.exports: any;
}

declare module 'rambda/src/both.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/clamp' {
  declare module.exports: any;
}

declare module 'rambda/src/clamp.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/clone' {
  declare module.exports: any;
}

declare module 'rambda/src/clone.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/complement' {
  declare module.exports: any;
}

declare module 'rambda/src/complement.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/compose' {
  declare module.exports: any;
}

declare module 'rambda/src/compose.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/concat' {
  declare module.exports: any;
}

declare module 'rambda/src/concat.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/cond' {
  declare module.exports: any;
}

declare module 'rambda/src/cond.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/converge' {
  declare module.exports: any;
}

declare module 'rambda/src/converge.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/curry' {
  declare module.exports: any;
}

declare module 'rambda/src/curry.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/curryN' {
  declare module.exports: any;
}

declare module 'rambda/src/curryN.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/dec' {
  declare module.exports: any;
}

declare module 'rambda/src/dec.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/defaultTo' {
  declare module.exports: any;
}

declare module 'rambda/src/defaultTo.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/difference' {
  declare module.exports: any;
}

declare module 'rambda/src/difference.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/dissoc' {
  declare module.exports: any;
}

declare module 'rambda/src/dissoc.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/divide' {
  declare module.exports: any;
}

declare module 'rambda/src/divide.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/drop' {
  declare module.exports: any;
}

declare module 'rambda/src/drop.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/src/dropLast.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/either' {
  declare module.exports: any;
}

declare module 'rambda/src/either.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/endsWith' {
  declare module.exports: any;
}

declare module 'rambda/src/endsWith.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/equals' {
  declare module.exports: any;
}

declare module 'rambda/src/equals.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/F' {
  declare module.exports: any;
}

declare module 'rambda/src/filter' {
  declare module.exports: any;
}

declare module 'rambda/src/filter.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/find' {
  declare module.exports: any;
}

declare module 'rambda/src/find.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/src/findIndex.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/findLast' {
  declare module.exports: any;
}

declare module 'rambda/src/findLast.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/findLastIndex' {
  declare module.exports: any;
}

declare module 'rambda/src/findLastIndex.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/flatten' {
  declare module.exports: any;
}

declare module 'rambda/src/flatten.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/flip' {
  declare module.exports: any;
}

declare module 'rambda/src/flip.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/forEach' {
  declare module.exports: any;
}

declare module 'rambda/src/forEach.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/fromPairs' {
  declare module.exports: any;
}

declare module 'rambda/src/fromPairs.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/groupBy' {
  declare module.exports: any;
}

declare module 'rambda/src/groupBy.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/groupWith' {
  declare module.exports: any;
}

declare module 'rambda/src/groupWith.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/has' {
  declare module.exports: any;
}

declare module 'rambda/src/has.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/head' {
  declare module.exports: any;
}

declare module 'rambda/src/head.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/identical' {
  declare module.exports: any;
}

declare module 'rambda/src/identical.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/identity' {
  declare module.exports: any;
}

declare module 'rambda/src/identity.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/ifElse' {
  declare module.exports: any;
}

declare module 'rambda/src/ifElse.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/inc' {
  declare module.exports: any;
}

declare module 'rambda/src/inc.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/includes' {
  declare module.exports: any;
}

declare module 'rambda/src/includes.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/indexBy' {
  declare module.exports: any;
}

declare module 'rambda/src/indexBy.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/src/indexOf.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/init' {
  declare module.exports: any;
}

declare module 'rambda/src/init.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/internal/_isInteger' {
  declare module.exports: any;
}

declare module 'rambda/src/internal/_objectIs' {
  declare module.exports: any;
}

declare module 'rambda/src/internal/baseSlice' {
  declare module.exports: any;
}

declare module 'rambda/src/intersection' {
  declare module.exports: any;
}

declare module 'rambda/src/intersection.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/intersperse' {
  declare module.exports: any;
}

declare module 'rambda/src/intersperse.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/is' {
  declare module.exports: any;
}

declare module 'rambda/src/is.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/isEmpty' {
  declare module.exports: any;
}

declare module 'rambda/src/isEmpty.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/isNil' {
  declare module.exports: any;
}

declare module 'rambda/src/isNil.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/join' {
  declare module.exports: any;
}

declare module 'rambda/src/join.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/keys' {
  declare module.exports: any;
}

declare module 'rambda/src/keys.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/last' {
  declare module.exports: any;
}

declare module 'rambda/src/last.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/lastIndexOf' {
  declare module.exports: any;
}

declare module 'rambda/src/lastIndexOf.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/length' {
  declare module.exports: any;
}

declare module 'rambda/src/length.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/lens' {
  declare module.exports: any;
}

declare module 'rambda/src/lenses.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/lensIndex' {
  declare module.exports: any;
}

declare module 'rambda/src/lensIndex.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/lensPath' {
  declare module.exports: any;
}

declare module 'rambda/src/lensPath.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/lensProp' {
  declare module.exports: any;
}

declare module 'rambda/src/lensProp.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/map' {
  declare module.exports: any;
}

declare module 'rambda/src/map.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/match' {
  declare module.exports: any;
}

declare module 'rambda/src/match.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/mathMod' {
  declare module.exports: any;
}

declare module 'rambda/src/mathMod.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/max' {
  declare module.exports: any;
}

declare module 'rambda/src/max.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/maxBy' {
  declare module.exports: any;
}

declare module 'rambda/src/maxBy.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/mean' {
  declare module.exports: any;
}

declare module 'rambda/src/mean.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/median' {
  declare module.exports: any;
}

declare module 'rambda/src/median.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/merge' {
  declare module.exports: any;
}

declare module 'rambda/src/merge.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/min' {
  declare module.exports: any;
}

declare module 'rambda/src/min.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/minBy' {
  declare module.exports: any;
}

declare module 'rambda/src/minBy.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/modulo' {
  declare module.exports: any;
}

declare module 'rambda/src/modulo.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/multiply' {
  declare module.exports: any;
}

declare module 'rambda/src/multiply.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/negate' {
  declare module.exports: any;
}

declare module 'rambda/src/negate.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/none' {
  declare module.exports: any;
}

declare module 'rambda/src/none.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/not' {
  declare module.exports: any;
}

declare module 'rambda/src/not.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/nth' {
  declare module.exports: any;
}

declare module 'rambda/src/nth.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/omit' {
  declare module.exports: any;
}

declare module 'rambda/src/omit.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/over' {
  declare module.exports: any;
}

declare module 'rambda/src/partial' {
  declare module.exports: any;
}

declare module 'rambda/src/partial.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/path' {
  declare module.exports: any;
}

declare module 'rambda/src/path.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/pathOr' {
  declare module.exports: any;
}

declare module 'rambda/src/pathOr.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/paths' {
  declare module.exports: any;
}

declare module 'rambda/src/paths.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/pick' {
  declare module.exports: any;
}

declare module 'rambda/src/pick.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/pickAll' {
  declare module.exports: any;
}

declare module 'rambda/src/pickAll.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/pipe' {
  declare module.exports: any;
}

declare module 'rambda/src/pipe.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/pluck' {
  declare module.exports: any;
}

declare module 'rambda/src/pluck.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/prepend' {
  declare module.exports: any;
}

declare module 'rambda/src/prepend.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/product' {
  declare module.exports: any;
}

declare module 'rambda/src/product.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/prop' {
  declare module.exports: any;
}

declare module 'rambda/src/prop.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/propEq' {
  declare module.exports: any;
}

declare module 'rambda/src/propEq.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/propIs' {
  declare module.exports: any;
}

declare module 'rambda/src/propIs.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/propOr' {
  declare module.exports: any;
}

declare module 'rambda/src/propOr.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/range' {
  declare module.exports: any;
}

declare module 'rambda/src/range.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/reduce' {
  declare module.exports: any;
}

declare module 'rambda/src/reduce.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/reject' {
  declare module.exports: any;
}

declare module 'rambda/src/reject.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/repeat' {
  declare module.exports: any;
}

declare module 'rambda/src/repeat.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/replace' {
  declare module.exports: any;
}

declare module 'rambda/src/replace.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/reverse' {
  declare module.exports: any;
}

declare module 'rambda/src/reverse.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/set' {
  declare module.exports: any;
}

declare module 'rambda/src/slice' {
  declare module.exports: any;
}

declare module 'rambda/src/slice.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/sort' {
  declare module.exports: any;
}

declare module 'rambda/src/sort.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/sortBy' {
  declare module.exports: any;
}

declare module 'rambda/src/sortBy.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/split' {
  declare module.exports: any;
}

declare module 'rambda/src/split.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/splitEvery' {
  declare module.exports: any;
}

declare module 'rambda/src/splitEvery.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/startsWith' {
  declare module.exports: any;
}

declare module 'rambda/src/startsWith.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/subtract' {
  declare module.exports: any;
}

declare module 'rambda/src/subtract.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/sum' {
  declare module.exports: any;
}

declare module 'rambda/src/sum.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/symmetricDifference' {
  declare module.exports: any;
}

declare module 'rambda/src/symmetricDifference.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/T' {
  declare module.exports: any;
}

declare module 'rambda/src/tail' {
  declare module.exports: any;
}

declare module 'rambda/src/tail.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/take' {
  declare module.exports: any;
}

declare module 'rambda/src/take.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/takeLast' {
  declare module.exports: any;
}

declare module 'rambda/src/takeLast.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/tap' {
  declare module.exports: any;
}

declare module 'rambda/src/tap.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/testMethod' {
  declare module.exports: any;
}

declare module 'rambda/src/testMethod.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/times' {
  declare module.exports: any;
}

declare module 'rambda/src/times.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/toLower' {
  declare module.exports: any;
}

declare module 'rambda/src/toLower.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/toPairs' {
  declare module.exports: any;
}

declare module 'rambda/src/toPairs.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/toString' {
  declare module.exports: any;
}

declare module 'rambda/src/toString.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/toUpper' {
  declare module.exports: any;
}

declare module 'rambda/src/toUpper.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/transpose' {
  declare module.exports: any;
}

declare module 'rambda/src/transpose.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/trim' {
  declare module.exports: any;
}

declare module 'rambda/src/trim.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/type' {
  declare module.exports: any;
}

declare module 'rambda/src/type.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/uniq' {
  declare module.exports: any;
}

declare module 'rambda/src/uniq.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/uniqWith' {
  declare module.exports: any;
}

declare module 'rambda/src/uniqWith.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/update' {
  declare module.exports: any;
}

declare module 'rambda/src/update.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/values' {
  declare module.exports: any;
}

declare module 'rambda/src/values.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/view' {
  declare module.exports: any;
}

declare module 'rambda/src/without' {
  declare module.exports: any;
}

declare module 'rambda/src/without.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/xor' {
  declare module.exports: any;
}

declare module 'rambda/src/xor.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/zip' {
  declare module.exports: any;
}

declare module 'rambda/src/zip.spec' {
  declare module.exports: any;
}

declare module 'rambda/src/zipObj' {
  declare module.exports: any;
}

declare module 'rambda/src/zipObj.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rambda/dist/rambda.esm.js' {
  declare module.exports: $Exports<'rambda/dist/rambda.esm'>;
}
declare module 'rambda/dist/rambda.js' {
  declare module.exports: $Exports<'rambda/dist/rambda'>;
}
declare module 'rambda/dist/rambda.umd.js' {
  declare module.exports: $Exports<'rambda/dist/rambda.umd'>;
}
declare module 'rambda/src/_build.spec.js' {
  declare module.exports: $Exports<'rambda/src/_build.spec'>;
}
declare module 'rambda/src/_typings.spec.js' {
  declare module.exports: $Exports<'rambda/src/_typings.spec'>;
}
declare module 'rambda/src/add.js' {
  declare module.exports: $Exports<'rambda/src/add'>;
}
declare module 'rambda/src/add.spec.js' {
  declare module.exports: $Exports<'rambda/src/add.spec'>;
}
declare module 'rambda/src/adjust.js' {
  declare module.exports: $Exports<'rambda/src/adjust'>;
}
declare module 'rambda/src/adjust.spec.js' {
  declare module.exports: $Exports<'rambda/src/adjust.spec'>;
}
declare module 'rambda/src/all.js' {
  declare module.exports: $Exports<'rambda/src/all'>;
}
declare module 'rambda/src/all.spec.js' {
  declare module.exports: $Exports<'rambda/src/all.spec'>;
}
declare module 'rambda/src/allPass.js' {
  declare module.exports: $Exports<'rambda/src/allPass'>;
}
declare module 'rambda/src/allPass.spec.js' {
  declare module.exports: $Exports<'rambda/src/allPass.spec'>;
}
declare module 'rambda/src/always.js' {
  declare module.exports: $Exports<'rambda/src/always'>;
}
declare module 'rambda/src/always.spec.js' {
  declare module.exports: $Exports<'rambda/src/always.spec'>;
}
declare module 'rambda/src/and.js' {
  declare module.exports: $Exports<'rambda/src/and'>;
}
declare module 'rambda/src/and.spec.js' {
  declare module.exports: $Exports<'rambda/src/and.spec'>;
}
declare module 'rambda/src/any.js' {
  declare module.exports: $Exports<'rambda/src/any'>;
}
declare module 'rambda/src/any.spec.js' {
  declare module.exports: $Exports<'rambda/src/any.spec'>;
}
declare module 'rambda/src/anyPass.js' {
  declare module.exports: $Exports<'rambda/src/anyPass'>;
}
declare module 'rambda/src/anyPass.spec.js' {
  declare module.exports: $Exports<'rambda/src/anyPass.spec'>;
}
declare module 'rambda/src/append.js' {
  declare module.exports: $Exports<'rambda/src/append'>;
}
declare module 'rambda/src/append.spec.js' {
  declare module.exports: $Exports<'rambda/src/append.spec'>;
}
declare module 'rambda/src/applySpec.js' {
  declare module.exports: $Exports<'rambda/src/applySpec'>;
}
declare module 'rambda/src/applySpec.spec.js' {
  declare module.exports: $Exports<'rambda/src/applySpec.spec'>;
}
declare module 'rambda/src/assoc.js' {
  declare module.exports: $Exports<'rambda/src/assoc'>;
}
declare module 'rambda/src/assoc.spec.js' {
  declare module.exports: $Exports<'rambda/src/assoc.spec'>;
}
declare module 'rambda/src/assocPath.js' {
  declare module.exports: $Exports<'rambda/src/assocPath'>;
}
declare module 'rambda/src/assocPath.spec.js' {
  declare module.exports: $Exports<'rambda/src/assocPath.spec'>;
}
declare module 'rambda/src/both.js' {
  declare module.exports: $Exports<'rambda/src/both'>;
}
declare module 'rambda/src/both.spec.js' {
  declare module.exports: $Exports<'rambda/src/both.spec'>;
}
declare module 'rambda/src/clamp.js' {
  declare module.exports: $Exports<'rambda/src/clamp'>;
}
declare module 'rambda/src/clamp.spec.js' {
  declare module.exports: $Exports<'rambda/src/clamp.spec'>;
}
declare module 'rambda/src/clone.js' {
  declare module.exports: $Exports<'rambda/src/clone'>;
}
declare module 'rambda/src/clone.spec.js' {
  declare module.exports: $Exports<'rambda/src/clone.spec'>;
}
declare module 'rambda/src/complement.js' {
  declare module.exports: $Exports<'rambda/src/complement'>;
}
declare module 'rambda/src/complement.spec.js' {
  declare module.exports: $Exports<'rambda/src/complement.spec'>;
}
declare module 'rambda/src/compose.js' {
  declare module.exports: $Exports<'rambda/src/compose'>;
}
declare module 'rambda/src/compose.spec.js' {
  declare module.exports: $Exports<'rambda/src/compose.spec'>;
}
declare module 'rambda/src/concat.js' {
  declare module.exports: $Exports<'rambda/src/concat'>;
}
declare module 'rambda/src/concat.spec.js' {
  declare module.exports: $Exports<'rambda/src/concat.spec'>;
}
declare module 'rambda/src/cond.js' {
  declare module.exports: $Exports<'rambda/src/cond'>;
}
declare module 'rambda/src/cond.spec.js' {
  declare module.exports: $Exports<'rambda/src/cond.spec'>;
}
declare module 'rambda/src/converge.js' {
  declare module.exports: $Exports<'rambda/src/converge'>;
}
declare module 'rambda/src/converge.spec.js' {
  declare module.exports: $Exports<'rambda/src/converge.spec'>;
}
declare module 'rambda/src/curry.js' {
  declare module.exports: $Exports<'rambda/src/curry'>;
}
declare module 'rambda/src/curry.spec.js' {
  declare module.exports: $Exports<'rambda/src/curry.spec'>;
}
declare module 'rambda/src/curryN.js' {
  declare module.exports: $Exports<'rambda/src/curryN'>;
}
declare module 'rambda/src/curryN.spec.js' {
  declare module.exports: $Exports<'rambda/src/curryN.spec'>;
}
declare module 'rambda/src/dec.js' {
  declare module.exports: $Exports<'rambda/src/dec'>;
}
declare module 'rambda/src/dec.spec.js' {
  declare module.exports: $Exports<'rambda/src/dec.spec'>;
}
declare module 'rambda/src/defaultTo.js' {
  declare module.exports: $Exports<'rambda/src/defaultTo'>;
}
declare module 'rambda/src/defaultTo.spec.js' {
  declare module.exports: $Exports<'rambda/src/defaultTo.spec'>;
}
declare module 'rambda/src/difference.js' {
  declare module.exports: $Exports<'rambda/src/difference'>;
}
declare module 'rambda/src/difference.spec.js' {
  declare module.exports: $Exports<'rambda/src/difference.spec'>;
}
declare module 'rambda/src/dissoc.js' {
  declare module.exports: $Exports<'rambda/src/dissoc'>;
}
declare module 'rambda/src/dissoc.spec.js' {
  declare module.exports: $Exports<'rambda/src/dissoc.spec'>;
}
declare module 'rambda/src/divide.js' {
  declare module.exports: $Exports<'rambda/src/divide'>;
}
declare module 'rambda/src/divide.spec.js' {
  declare module.exports: $Exports<'rambda/src/divide.spec'>;
}
declare module 'rambda/src/drop.js' {
  declare module.exports: $Exports<'rambda/src/drop'>;
}
declare module 'rambda/src/drop.spec.js' {
  declare module.exports: $Exports<'rambda/src/drop.spec'>;
}
declare module 'rambda/src/dropLast.js' {
  declare module.exports: $Exports<'rambda/src/dropLast'>;
}
declare module 'rambda/src/dropLast.spec.js' {
  declare module.exports: $Exports<'rambda/src/dropLast.spec'>;
}
declare module 'rambda/src/either.js' {
  declare module.exports: $Exports<'rambda/src/either'>;
}
declare module 'rambda/src/either.spec.js' {
  declare module.exports: $Exports<'rambda/src/either.spec'>;
}
declare module 'rambda/src/endsWith.js' {
  declare module.exports: $Exports<'rambda/src/endsWith'>;
}
declare module 'rambda/src/endsWith.spec.js' {
  declare module.exports: $Exports<'rambda/src/endsWith.spec'>;
}
declare module 'rambda/src/equals.js' {
  declare module.exports: $Exports<'rambda/src/equals'>;
}
declare module 'rambda/src/equals.spec.js' {
  declare module.exports: $Exports<'rambda/src/equals.spec'>;
}
declare module 'rambda/src/F.js' {
  declare module.exports: $Exports<'rambda/src/F'>;
}
declare module 'rambda/src/filter.js' {
  declare module.exports: $Exports<'rambda/src/filter'>;
}
declare module 'rambda/src/filter.spec.js' {
  declare module.exports: $Exports<'rambda/src/filter.spec'>;
}
declare module 'rambda/src/find.js' {
  declare module.exports: $Exports<'rambda/src/find'>;
}
declare module 'rambda/src/find.spec.js' {
  declare module.exports: $Exports<'rambda/src/find.spec'>;
}
declare module 'rambda/src/findIndex.js' {
  declare module.exports: $Exports<'rambda/src/findIndex'>;
}
declare module 'rambda/src/findIndex.spec.js' {
  declare module.exports: $Exports<'rambda/src/findIndex.spec'>;
}
declare module 'rambda/src/findLast.js' {
  declare module.exports: $Exports<'rambda/src/findLast'>;
}
declare module 'rambda/src/findLast.spec.js' {
  declare module.exports: $Exports<'rambda/src/findLast.spec'>;
}
declare module 'rambda/src/findLastIndex.js' {
  declare module.exports: $Exports<'rambda/src/findLastIndex'>;
}
declare module 'rambda/src/findLastIndex.spec.js' {
  declare module.exports: $Exports<'rambda/src/findLastIndex.spec'>;
}
declare module 'rambda/src/flatten.js' {
  declare module.exports: $Exports<'rambda/src/flatten'>;
}
declare module 'rambda/src/flatten.spec.js' {
  declare module.exports: $Exports<'rambda/src/flatten.spec'>;
}
declare module 'rambda/src/flip.js' {
  declare module.exports: $Exports<'rambda/src/flip'>;
}
declare module 'rambda/src/flip.spec.js' {
  declare module.exports: $Exports<'rambda/src/flip.spec'>;
}
declare module 'rambda/src/forEach.js' {
  declare module.exports: $Exports<'rambda/src/forEach'>;
}
declare module 'rambda/src/forEach.spec.js' {
  declare module.exports: $Exports<'rambda/src/forEach.spec'>;
}
declare module 'rambda/src/fromPairs.js' {
  declare module.exports: $Exports<'rambda/src/fromPairs'>;
}
declare module 'rambda/src/fromPairs.spec.js' {
  declare module.exports: $Exports<'rambda/src/fromPairs.spec'>;
}
declare module 'rambda/src/groupBy.js' {
  declare module.exports: $Exports<'rambda/src/groupBy'>;
}
declare module 'rambda/src/groupBy.spec.js' {
  declare module.exports: $Exports<'rambda/src/groupBy.spec'>;
}
declare module 'rambda/src/groupWith.js' {
  declare module.exports: $Exports<'rambda/src/groupWith'>;
}
declare module 'rambda/src/groupWith.spec.js' {
  declare module.exports: $Exports<'rambda/src/groupWith.spec'>;
}
declare module 'rambda/src/has.js' {
  declare module.exports: $Exports<'rambda/src/has'>;
}
declare module 'rambda/src/has.spec.js' {
  declare module.exports: $Exports<'rambda/src/has.spec'>;
}
declare module 'rambda/src/head.js' {
  declare module.exports: $Exports<'rambda/src/head'>;
}
declare module 'rambda/src/head.spec.js' {
  declare module.exports: $Exports<'rambda/src/head.spec'>;
}
declare module 'rambda/src/identical.js' {
  declare module.exports: $Exports<'rambda/src/identical'>;
}
declare module 'rambda/src/identical.spec.js' {
  declare module.exports: $Exports<'rambda/src/identical.spec'>;
}
declare module 'rambda/src/identity.js' {
  declare module.exports: $Exports<'rambda/src/identity'>;
}
declare module 'rambda/src/identity.spec.js' {
  declare module.exports: $Exports<'rambda/src/identity.spec'>;
}
declare module 'rambda/src/ifElse.js' {
  declare module.exports: $Exports<'rambda/src/ifElse'>;
}
declare module 'rambda/src/ifElse.spec.js' {
  declare module.exports: $Exports<'rambda/src/ifElse.spec'>;
}
declare module 'rambda/src/inc.js' {
  declare module.exports: $Exports<'rambda/src/inc'>;
}
declare module 'rambda/src/inc.spec.js' {
  declare module.exports: $Exports<'rambda/src/inc.spec'>;
}
declare module 'rambda/src/includes.js' {
  declare module.exports: $Exports<'rambda/src/includes'>;
}
declare module 'rambda/src/includes.spec.js' {
  declare module.exports: $Exports<'rambda/src/includes.spec'>;
}
declare module 'rambda/src/indexBy.js' {
  declare module.exports: $Exports<'rambda/src/indexBy'>;
}
declare module 'rambda/src/indexBy.spec.js' {
  declare module.exports: $Exports<'rambda/src/indexBy.spec'>;
}
declare module 'rambda/src/indexOf.js' {
  declare module.exports: $Exports<'rambda/src/indexOf'>;
}
declare module 'rambda/src/indexOf.spec.js' {
  declare module.exports: $Exports<'rambda/src/indexOf.spec'>;
}
declare module 'rambda/src/init.js' {
  declare module.exports: $Exports<'rambda/src/init'>;
}
declare module 'rambda/src/init.spec.js' {
  declare module.exports: $Exports<'rambda/src/init.spec'>;
}
declare module 'rambda/src/internal/_isInteger.js' {
  declare module.exports: $Exports<'rambda/src/internal/_isInteger'>;
}
declare module 'rambda/src/internal/_objectIs.js' {
  declare module.exports: $Exports<'rambda/src/internal/_objectIs'>;
}
declare module 'rambda/src/internal/baseSlice.js' {
  declare module.exports: $Exports<'rambda/src/internal/baseSlice'>;
}
declare module 'rambda/src/intersection.js' {
  declare module.exports: $Exports<'rambda/src/intersection'>;
}
declare module 'rambda/src/intersection.spec.js' {
  declare module.exports: $Exports<'rambda/src/intersection.spec'>;
}
declare module 'rambda/src/intersperse.js' {
  declare module.exports: $Exports<'rambda/src/intersperse'>;
}
declare module 'rambda/src/intersperse.spec.js' {
  declare module.exports: $Exports<'rambda/src/intersperse.spec'>;
}
declare module 'rambda/src/is.js' {
  declare module.exports: $Exports<'rambda/src/is'>;
}
declare module 'rambda/src/is.spec.js' {
  declare module.exports: $Exports<'rambda/src/is.spec'>;
}
declare module 'rambda/src/isEmpty.js' {
  declare module.exports: $Exports<'rambda/src/isEmpty'>;
}
declare module 'rambda/src/isEmpty.spec.js' {
  declare module.exports: $Exports<'rambda/src/isEmpty.spec'>;
}
declare module 'rambda/src/isNil.js' {
  declare module.exports: $Exports<'rambda/src/isNil'>;
}
declare module 'rambda/src/isNil.spec.js' {
  declare module.exports: $Exports<'rambda/src/isNil.spec'>;
}
declare module 'rambda/src/join.js' {
  declare module.exports: $Exports<'rambda/src/join'>;
}
declare module 'rambda/src/join.spec.js' {
  declare module.exports: $Exports<'rambda/src/join.spec'>;
}
declare module 'rambda/src/keys.js' {
  declare module.exports: $Exports<'rambda/src/keys'>;
}
declare module 'rambda/src/keys.spec.js' {
  declare module.exports: $Exports<'rambda/src/keys.spec'>;
}
declare module 'rambda/src/last.js' {
  declare module.exports: $Exports<'rambda/src/last'>;
}
declare module 'rambda/src/last.spec.js' {
  declare module.exports: $Exports<'rambda/src/last.spec'>;
}
declare module 'rambda/src/lastIndexOf.js' {
  declare module.exports: $Exports<'rambda/src/lastIndexOf'>;
}
declare module 'rambda/src/lastIndexOf.spec.js' {
  declare module.exports: $Exports<'rambda/src/lastIndexOf.spec'>;
}
declare module 'rambda/src/length.js' {
  declare module.exports: $Exports<'rambda/src/length'>;
}
declare module 'rambda/src/length.spec.js' {
  declare module.exports: $Exports<'rambda/src/length.spec'>;
}
declare module 'rambda/src/lens.js' {
  declare module.exports: $Exports<'rambda/src/lens'>;
}
declare module 'rambda/src/lenses.spec.js' {
  declare module.exports: $Exports<'rambda/src/lenses.spec'>;
}
declare module 'rambda/src/lensIndex.js' {
  declare module.exports: $Exports<'rambda/src/lensIndex'>;
}
declare module 'rambda/src/lensIndex.spec.js' {
  declare module.exports: $Exports<'rambda/src/lensIndex.spec'>;
}
declare module 'rambda/src/lensPath.js' {
  declare module.exports: $Exports<'rambda/src/lensPath'>;
}
declare module 'rambda/src/lensPath.spec.js' {
  declare module.exports: $Exports<'rambda/src/lensPath.spec'>;
}
declare module 'rambda/src/lensProp.js' {
  declare module.exports: $Exports<'rambda/src/lensProp'>;
}
declare module 'rambda/src/lensProp.spec.js' {
  declare module.exports: $Exports<'rambda/src/lensProp.spec'>;
}
declare module 'rambda/src/map.js' {
  declare module.exports: $Exports<'rambda/src/map'>;
}
declare module 'rambda/src/map.spec.js' {
  declare module.exports: $Exports<'rambda/src/map.spec'>;
}
declare module 'rambda/src/match.js' {
  declare module.exports: $Exports<'rambda/src/match'>;
}
declare module 'rambda/src/match.spec.js' {
  declare module.exports: $Exports<'rambda/src/match.spec'>;
}
declare module 'rambda/src/mathMod.js' {
  declare module.exports: $Exports<'rambda/src/mathMod'>;
}
declare module 'rambda/src/mathMod.spec.js' {
  declare module.exports: $Exports<'rambda/src/mathMod.spec'>;
}
declare module 'rambda/src/max.js' {
  declare module.exports: $Exports<'rambda/src/max'>;
}
declare module 'rambda/src/max.spec.js' {
  declare module.exports: $Exports<'rambda/src/max.spec'>;
}
declare module 'rambda/src/maxBy.js' {
  declare module.exports: $Exports<'rambda/src/maxBy'>;
}
declare module 'rambda/src/maxBy.spec.js' {
  declare module.exports: $Exports<'rambda/src/maxBy.spec'>;
}
declare module 'rambda/src/mean.js' {
  declare module.exports: $Exports<'rambda/src/mean'>;
}
declare module 'rambda/src/mean.spec.js' {
  declare module.exports: $Exports<'rambda/src/mean.spec'>;
}
declare module 'rambda/src/median.js' {
  declare module.exports: $Exports<'rambda/src/median'>;
}
declare module 'rambda/src/median.spec.js' {
  declare module.exports: $Exports<'rambda/src/median.spec'>;
}
declare module 'rambda/src/merge.js' {
  declare module.exports: $Exports<'rambda/src/merge'>;
}
declare module 'rambda/src/merge.spec.js' {
  declare module.exports: $Exports<'rambda/src/merge.spec'>;
}
declare module 'rambda/src/min.js' {
  declare module.exports: $Exports<'rambda/src/min'>;
}
declare module 'rambda/src/min.spec.js' {
  declare module.exports: $Exports<'rambda/src/min.spec'>;
}
declare module 'rambda/src/minBy.js' {
  declare module.exports: $Exports<'rambda/src/minBy'>;
}
declare module 'rambda/src/minBy.spec.js' {
  declare module.exports: $Exports<'rambda/src/minBy.spec'>;
}
declare module 'rambda/src/modulo.js' {
  declare module.exports: $Exports<'rambda/src/modulo'>;
}
declare module 'rambda/src/modulo.spec.js' {
  declare module.exports: $Exports<'rambda/src/modulo.spec'>;
}
declare module 'rambda/src/multiply.js' {
  declare module.exports: $Exports<'rambda/src/multiply'>;
}
declare module 'rambda/src/multiply.spec.js' {
  declare module.exports: $Exports<'rambda/src/multiply.spec'>;
}
declare module 'rambda/src/negate.js' {
  declare module.exports: $Exports<'rambda/src/negate'>;
}
declare module 'rambda/src/negate.spec.js' {
  declare module.exports: $Exports<'rambda/src/negate.spec'>;
}
declare module 'rambda/src/none.js' {
  declare module.exports: $Exports<'rambda/src/none'>;
}
declare module 'rambda/src/none.spec.js' {
  declare module.exports: $Exports<'rambda/src/none.spec'>;
}
declare module 'rambda/src/not.js' {
  declare module.exports: $Exports<'rambda/src/not'>;
}
declare module 'rambda/src/not.spec.js' {
  declare module.exports: $Exports<'rambda/src/not.spec'>;
}
declare module 'rambda/src/nth.js' {
  declare module.exports: $Exports<'rambda/src/nth'>;
}
declare module 'rambda/src/nth.spec.js' {
  declare module.exports: $Exports<'rambda/src/nth.spec'>;
}
declare module 'rambda/src/omit.js' {
  declare module.exports: $Exports<'rambda/src/omit'>;
}
declare module 'rambda/src/omit.spec.js' {
  declare module.exports: $Exports<'rambda/src/omit.spec'>;
}
declare module 'rambda/src/over.js' {
  declare module.exports: $Exports<'rambda/src/over'>;
}
declare module 'rambda/src/partial.js' {
  declare module.exports: $Exports<'rambda/src/partial'>;
}
declare module 'rambda/src/partial.spec.js' {
  declare module.exports: $Exports<'rambda/src/partial.spec'>;
}
declare module 'rambda/src/path.js' {
  declare module.exports: $Exports<'rambda/src/path'>;
}
declare module 'rambda/src/path.spec.js' {
  declare module.exports: $Exports<'rambda/src/path.spec'>;
}
declare module 'rambda/src/pathOr.js' {
  declare module.exports: $Exports<'rambda/src/pathOr'>;
}
declare module 'rambda/src/pathOr.spec.js' {
  declare module.exports: $Exports<'rambda/src/pathOr.spec'>;
}
declare module 'rambda/src/paths.js' {
  declare module.exports: $Exports<'rambda/src/paths'>;
}
declare module 'rambda/src/paths.spec.js' {
  declare module.exports: $Exports<'rambda/src/paths.spec'>;
}
declare module 'rambda/src/pick.js' {
  declare module.exports: $Exports<'rambda/src/pick'>;
}
declare module 'rambda/src/pick.spec.js' {
  declare module.exports: $Exports<'rambda/src/pick.spec'>;
}
declare module 'rambda/src/pickAll.js' {
  declare module.exports: $Exports<'rambda/src/pickAll'>;
}
declare module 'rambda/src/pickAll.spec.js' {
  declare module.exports: $Exports<'rambda/src/pickAll.spec'>;
}
declare module 'rambda/src/pipe.js' {
  declare module.exports: $Exports<'rambda/src/pipe'>;
}
declare module 'rambda/src/pipe.spec.js' {
  declare module.exports: $Exports<'rambda/src/pipe.spec'>;
}
declare module 'rambda/src/pluck.js' {
  declare module.exports: $Exports<'rambda/src/pluck'>;
}
declare module 'rambda/src/pluck.spec.js' {
  declare module.exports: $Exports<'rambda/src/pluck.spec'>;
}
declare module 'rambda/src/prepend.js' {
  declare module.exports: $Exports<'rambda/src/prepend'>;
}
declare module 'rambda/src/prepend.spec.js' {
  declare module.exports: $Exports<'rambda/src/prepend.spec'>;
}
declare module 'rambda/src/product.js' {
  declare module.exports: $Exports<'rambda/src/product'>;
}
declare module 'rambda/src/product.spec.js' {
  declare module.exports: $Exports<'rambda/src/product.spec'>;
}
declare module 'rambda/src/prop.js' {
  declare module.exports: $Exports<'rambda/src/prop'>;
}
declare module 'rambda/src/prop.spec.js' {
  declare module.exports: $Exports<'rambda/src/prop.spec'>;
}
declare module 'rambda/src/propEq.js' {
  declare module.exports: $Exports<'rambda/src/propEq'>;
}
declare module 'rambda/src/propEq.spec.js' {
  declare module.exports: $Exports<'rambda/src/propEq.spec'>;
}
declare module 'rambda/src/propIs.js' {
  declare module.exports: $Exports<'rambda/src/propIs'>;
}
declare module 'rambda/src/propIs.spec.js' {
  declare module.exports: $Exports<'rambda/src/propIs.spec'>;
}
declare module 'rambda/src/propOr.js' {
  declare module.exports: $Exports<'rambda/src/propOr'>;
}
declare module 'rambda/src/propOr.spec.js' {
  declare module.exports: $Exports<'rambda/src/propOr.spec'>;
}
declare module 'rambda/src/range.js' {
  declare module.exports: $Exports<'rambda/src/range'>;
}
declare module 'rambda/src/range.spec.js' {
  declare module.exports: $Exports<'rambda/src/range.spec'>;
}
declare module 'rambda/src/reduce.js' {
  declare module.exports: $Exports<'rambda/src/reduce'>;
}
declare module 'rambda/src/reduce.spec.js' {
  declare module.exports: $Exports<'rambda/src/reduce.spec'>;
}
declare module 'rambda/src/reject.js' {
  declare module.exports: $Exports<'rambda/src/reject'>;
}
declare module 'rambda/src/reject.spec.js' {
  declare module.exports: $Exports<'rambda/src/reject.spec'>;
}
declare module 'rambda/src/repeat.js' {
  declare module.exports: $Exports<'rambda/src/repeat'>;
}
declare module 'rambda/src/repeat.spec.js' {
  declare module.exports: $Exports<'rambda/src/repeat.spec'>;
}
declare module 'rambda/src/replace.js' {
  declare module.exports: $Exports<'rambda/src/replace'>;
}
declare module 'rambda/src/replace.spec.js' {
  declare module.exports: $Exports<'rambda/src/replace.spec'>;
}
declare module 'rambda/src/reverse.js' {
  declare module.exports: $Exports<'rambda/src/reverse'>;
}
declare module 'rambda/src/reverse.spec.js' {
  declare module.exports: $Exports<'rambda/src/reverse.spec'>;
}
declare module 'rambda/src/set.js' {
  declare module.exports: $Exports<'rambda/src/set'>;
}
declare module 'rambda/src/slice.js' {
  declare module.exports: $Exports<'rambda/src/slice'>;
}
declare module 'rambda/src/slice.spec.js' {
  declare module.exports: $Exports<'rambda/src/slice.spec'>;
}
declare module 'rambda/src/sort.js' {
  declare module.exports: $Exports<'rambda/src/sort'>;
}
declare module 'rambda/src/sort.spec.js' {
  declare module.exports: $Exports<'rambda/src/sort.spec'>;
}
declare module 'rambda/src/sortBy.js' {
  declare module.exports: $Exports<'rambda/src/sortBy'>;
}
declare module 'rambda/src/sortBy.spec.js' {
  declare module.exports: $Exports<'rambda/src/sortBy.spec'>;
}
declare module 'rambda/src/split.js' {
  declare module.exports: $Exports<'rambda/src/split'>;
}
declare module 'rambda/src/split.spec.js' {
  declare module.exports: $Exports<'rambda/src/split.spec'>;
}
declare module 'rambda/src/splitEvery.js' {
  declare module.exports: $Exports<'rambda/src/splitEvery'>;
}
declare module 'rambda/src/splitEvery.spec.js' {
  declare module.exports: $Exports<'rambda/src/splitEvery.spec'>;
}
declare module 'rambda/src/startsWith.js' {
  declare module.exports: $Exports<'rambda/src/startsWith'>;
}
declare module 'rambda/src/startsWith.spec.js' {
  declare module.exports: $Exports<'rambda/src/startsWith.spec'>;
}
declare module 'rambda/src/subtract.js' {
  declare module.exports: $Exports<'rambda/src/subtract'>;
}
declare module 'rambda/src/subtract.spec.js' {
  declare module.exports: $Exports<'rambda/src/subtract.spec'>;
}
declare module 'rambda/src/sum.js' {
  declare module.exports: $Exports<'rambda/src/sum'>;
}
declare module 'rambda/src/sum.spec.js' {
  declare module.exports: $Exports<'rambda/src/sum.spec'>;
}
declare module 'rambda/src/symmetricDifference.js' {
  declare module.exports: $Exports<'rambda/src/symmetricDifference'>;
}
declare module 'rambda/src/symmetricDifference.spec.js' {
  declare module.exports: $Exports<'rambda/src/symmetricDifference.spec'>;
}
declare module 'rambda/src/T.js' {
  declare module.exports: $Exports<'rambda/src/T'>;
}
declare module 'rambda/src/tail.js' {
  declare module.exports: $Exports<'rambda/src/tail'>;
}
declare module 'rambda/src/tail.spec.js' {
  declare module.exports: $Exports<'rambda/src/tail.spec'>;
}
declare module 'rambda/src/take.js' {
  declare module.exports: $Exports<'rambda/src/take'>;
}
declare module 'rambda/src/take.spec.js' {
  declare module.exports: $Exports<'rambda/src/take.spec'>;
}
declare module 'rambda/src/takeLast.js' {
  declare module.exports: $Exports<'rambda/src/takeLast'>;
}
declare module 'rambda/src/takeLast.spec.js' {
  declare module.exports: $Exports<'rambda/src/takeLast.spec'>;
}
declare module 'rambda/src/tap.js' {
  declare module.exports: $Exports<'rambda/src/tap'>;
}
declare module 'rambda/src/tap.spec.js' {
  declare module.exports: $Exports<'rambda/src/tap.spec'>;
}
declare module 'rambda/src/testMethod.js' {
  declare module.exports: $Exports<'rambda/src/testMethod'>;
}
declare module 'rambda/src/testMethod.spec.js' {
  declare module.exports: $Exports<'rambda/src/testMethod.spec'>;
}
declare module 'rambda/src/times.js' {
  declare module.exports: $Exports<'rambda/src/times'>;
}
declare module 'rambda/src/times.spec.js' {
  declare module.exports: $Exports<'rambda/src/times.spec'>;
}
declare module 'rambda/src/toLower.js' {
  declare module.exports: $Exports<'rambda/src/toLower'>;
}
declare module 'rambda/src/toLower.spec.js' {
  declare module.exports: $Exports<'rambda/src/toLower.spec'>;
}
declare module 'rambda/src/toPairs.js' {
  declare module.exports: $Exports<'rambda/src/toPairs'>;
}
declare module 'rambda/src/toPairs.spec.js' {
  declare module.exports: $Exports<'rambda/src/toPairs.spec'>;
}
declare module 'rambda/src/toString.js' {
  declare module.exports: $Exports<'rambda/src/toString'>;
}
declare module 'rambda/src/toString.spec.js' {
  declare module.exports: $Exports<'rambda/src/toString.spec'>;
}
declare module 'rambda/src/toUpper.js' {
  declare module.exports: $Exports<'rambda/src/toUpper'>;
}
declare module 'rambda/src/toUpper.spec.js' {
  declare module.exports: $Exports<'rambda/src/toUpper.spec'>;
}
declare module 'rambda/src/transpose.js' {
  declare module.exports: $Exports<'rambda/src/transpose'>;
}
declare module 'rambda/src/transpose.spec.js' {
  declare module.exports: $Exports<'rambda/src/transpose.spec'>;
}
declare module 'rambda/src/trim.js' {
  declare module.exports: $Exports<'rambda/src/trim'>;
}
declare module 'rambda/src/trim.spec.js' {
  declare module.exports: $Exports<'rambda/src/trim.spec'>;
}
declare module 'rambda/src/type.js' {
  declare module.exports: $Exports<'rambda/src/type'>;
}
declare module 'rambda/src/type.spec.js' {
  declare module.exports: $Exports<'rambda/src/type.spec'>;
}
declare module 'rambda/src/uniq.js' {
  declare module.exports: $Exports<'rambda/src/uniq'>;
}
declare module 'rambda/src/uniq.spec.js' {
  declare module.exports: $Exports<'rambda/src/uniq.spec'>;
}
declare module 'rambda/src/uniqWith.js' {
  declare module.exports: $Exports<'rambda/src/uniqWith'>;
}
declare module 'rambda/src/uniqWith.spec.js' {
  declare module.exports: $Exports<'rambda/src/uniqWith.spec'>;
}
declare module 'rambda/src/update.js' {
  declare module.exports: $Exports<'rambda/src/update'>;
}
declare module 'rambda/src/update.spec.js' {
  declare module.exports: $Exports<'rambda/src/update.spec'>;
}
declare module 'rambda/src/values.js' {
  declare module.exports: $Exports<'rambda/src/values'>;
}
declare module 'rambda/src/values.spec.js' {
  declare module.exports: $Exports<'rambda/src/values.spec'>;
}
declare module 'rambda/src/view.js' {
  declare module.exports: $Exports<'rambda/src/view'>;
}
declare module 'rambda/src/without.js' {
  declare module.exports: $Exports<'rambda/src/without'>;
}
declare module 'rambda/src/without.spec.js' {
  declare module.exports: $Exports<'rambda/src/without.spec'>;
}
declare module 'rambda/src/xor.js' {
  declare module.exports: $Exports<'rambda/src/xor'>;
}
declare module 'rambda/src/xor.spec.js' {
  declare module.exports: $Exports<'rambda/src/xor.spec'>;
}
declare module 'rambda/src/zip.js' {
  declare module.exports: $Exports<'rambda/src/zip'>;
}
declare module 'rambda/src/zip.spec.js' {
  declare module.exports: $Exports<'rambda/src/zip.spec'>;
}
declare module 'rambda/src/zipObj.js' {
  declare module.exports: $Exports<'rambda/src/zipObj'>;
}
declare module 'rambda/src/zipObj.spec.js' {
  declare module.exports: $Exports<'rambda/src/zipObj.spec'>;
}
