// flow-typed signature: 0a149e20bedaabaeb8fae6cd589fb503
// flow-typed version: <<STUB>>/react-contexify_v^4.0.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-contexify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-contexify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-contexify/dist/ReactContexify' {
  declare module.exports: any;
}

declare module 'react-contexify/jest.config' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/cloneItem' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/IconFont' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/Item' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/Menu' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/MenuProvider' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/Portal' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/Separator' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/components/Submenu' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/index' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/types/index' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/utils/actions' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/utils/contextMenu' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/utils/eventManager' {
  declare module.exports: any;
}

declare module 'react-contexify/lib/utils/styles' {
  declare module.exports: any;
}

declare module 'react-contexify/webpack.config.dev' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-contexify/dist/ReactContexify.js' {
  declare module.exports: $Exports<'react-contexify/dist/ReactContexify'>;
}
declare module 'react-contexify/jest.config.js' {
  declare module.exports: $Exports<'react-contexify/jest.config'>;
}
declare module 'react-contexify/lib/components/cloneItem.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/cloneItem'>;
}
declare module 'react-contexify/lib/components/IconFont.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/IconFont'>;
}
declare module 'react-contexify/lib/components/Item.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/Item'>;
}
declare module 'react-contexify/lib/components/Menu.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/Menu'>;
}
declare module 'react-contexify/lib/components/MenuProvider.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/MenuProvider'>;
}
declare module 'react-contexify/lib/components/Portal.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/Portal'>;
}
declare module 'react-contexify/lib/components/Separator.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/Separator'>;
}
declare module 'react-contexify/lib/components/Submenu.js' {
  declare module.exports: $Exports<'react-contexify/lib/components/Submenu'>;
}
declare module 'react-contexify/lib/index.js' {
  declare module.exports: $Exports<'react-contexify/lib/index'>;
}
declare module 'react-contexify/lib/types/index.js' {
  declare module.exports: $Exports<'react-contexify/lib/types/index'>;
}
declare module 'react-contexify/lib/utils/actions.js' {
  declare module.exports: $Exports<'react-contexify/lib/utils/actions'>;
}
declare module 'react-contexify/lib/utils/contextMenu.js' {
  declare module.exports: $Exports<'react-contexify/lib/utils/contextMenu'>;
}
declare module 'react-contexify/lib/utils/eventManager.js' {
  declare module.exports: $Exports<'react-contexify/lib/utils/eventManager'>;
}
declare module 'react-contexify/lib/utils/styles.js' {
  declare module.exports: $Exports<'react-contexify/lib/utils/styles'>;
}
declare module 'react-contexify/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-contexify/webpack.config.dev'>;
}
