// flow-typed signature: 9f2666bd686c463e3414de5112f42c47
// flow-typed version: <<STUB>>/react-resize-detector_v^4.2.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-resize-detector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-resize-detector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-resize-detector/lib/components/ChildWrapper' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/components/Reference' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/components/ResizeDetector' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/esm/components/ChildWrapper' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/esm/components/Reference' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/esm/components/ResizeDetector' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/esm/hoc/withResizeDetector' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/esm/index' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/esm/lib/utils' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/hoc/withResizeDetector' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/index' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-resize-detector/lib/components/ChildWrapper.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/components/ChildWrapper'>;
}
declare module 'react-resize-detector/lib/components/Reference.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/components/Reference'>;
}
declare module 'react-resize-detector/lib/components/ResizeDetector.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/components/ResizeDetector'>;
}
declare module 'react-resize-detector/lib/esm/components/ChildWrapper.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm/components/ChildWrapper'>;
}
declare module 'react-resize-detector/lib/esm/components/Reference.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm/components/Reference'>;
}
declare module 'react-resize-detector/lib/esm/components/ResizeDetector.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm/components/ResizeDetector'>;
}
declare module 'react-resize-detector/lib/esm/hoc/withResizeDetector.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm/hoc/withResizeDetector'>;
}
declare module 'react-resize-detector/lib/esm/index.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm/index'>;
}
declare module 'react-resize-detector/lib/esm/lib/utils.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm/lib/utils'>;
}
declare module 'react-resize-detector/lib/hoc/withResizeDetector.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/hoc/withResizeDetector'>;
}
declare module 'react-resize-detector/lib/index.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/index'>;
}
declare module 'react-resize-detector/lib/lib/utils.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/lib/utils'>;
}
