// flow-typed signature: 7c7f773fbab3c8f578fa4465c6f3848f
// flow-typed version: <<STUB>>/redtape_v^1.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redtape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redtape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redtape/example/example1-options' {
  declare module.exports: any;
}

declare module 'redtape/example/example1' {
  declare module.exports: any;
}

declare module 'redtape/example/example2-options' {
  declare module.exports: any;
}

declare module 'redtape/example/example2' {
  declare module.exports: any;
}

declare module 'redtape/example/example3-options' {
  declare module.exports: any;
}

declare module 'redtape/example/example3' {
  declare module.exports: any;
}

declare module 'redtape/ignore' {
  declare module.exports: any;
}

declare module 'redtape/test/index' {
  declare module.exports: any;
}

declare module 'redtape/test/options' {
  declare module.exports: any;
}

declare module 'redtape/test/plan' {
  declare module.exports: any;
}

declare module 'redtape/test/special/only' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redtape/example/example1-options.js' {
  declare module.exports: $Exports<'redtape/example/example1-options'>;
}
declare module 'redtape/example/example1.js' {
  declare module.exports: $Exports<'redtape/example/example1'>;
}
declare module 'redtape/example/example2-options.js' {
  declare module.exports: $Exports<'redtape/example/example2-options'>;
}
declare module 'redtape/example/example2.js' {
  declare module.exports: $Exports<'redtape/example/example2'>;
}
declare module 'redtape/example/example3-options.js' {
  declare module.exports: $Exports<'redtape/example/example3-options'>;
}
declare module 'redtape/example/example3.js' {
  declare module.exports: $Exports<'redtape/example/example3'>;
}
declare module 'redtape/ignore.js' {
  declare module.exports: $Exports<'redtape/ignore'>;
}
declare module 'redtape/index' {
  declare module.exports: $Exports<'redtape'>;
}
declare module 'redtape/index.js' {
  declare module.exports: $Exports<'redtape'>;
}
declare module 'redtape/test/index.js' {
  declare module.exports: $Exports<'redtape/test/index'>;
}
declare module 'redtape/test/options.js' {
  declare module.exports: $Exports<'redtape/test/options'>;
}
declare module 'redtape/test/plan.js' {
  declare module.exports: $Exports<'redtape/test/plan'>;
}
declare module 'redtape/test/special/only.js' {
  declare module.exports: $Exports<'redtape/test/special/only'>;
}
