// flow-typed signature: d2eb087189bacd6fd172e5fc063f0408
// flow-typed version: <<STUB>>/redux-testkit_v^1.0.6/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-testkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-testkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-testkit/dist/FlushThunks' {
  declare module.exports: any;
}

declare module 'redux-testkit/dist/index' {
  declare module.exports: any;
}

declare module 'redux-testkit/dist/Reducer' {
  declare module.exports: any;
}

declare module 'redux-testkit/dist/Selector' {
  declare module.exports: any;
}

declare module 'redux-testkit/dist/Thunk' {
  declare module.exports: any;
}

declare module 'redux-testkit/dist/utils' {
  declare module.exports: any;
}

declare module 'redux-testkit/src/FlushThunks' {
  declare module.exports: any;
}

declare module 'redux-testkit/src/index' {
  declare module.exports: any;
}

declare module 'redux-testkit/src/Reducer' {
  declare module.exports: any;
}

declare module 'redux-testkit/src/Selector' {
  declare module.exports: any;
}

declare module 'redux-testkit/src/Thunk' {
  declare module.exports: any;
}

declare module 'redux-testkit/src/utils' {
  declare module.exports: any;
}

declare module 'redux-testkit/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-testkit/dist/FlushThunks.js' {
  declare module.exports: $Exports<'redux-testkit/dist/FlushThunks'>;
}
declare module 'redux-testkit/dist/index.js' {
  declare module.exports: $Exports<'redux-testkit/dist/index'>;
}
declare module 'redux-testkit/dist/Reducer.js' {
  declare module.exports: $Exports<'redux-testkit/dist/Reducer'>;
}
declare module 'redux-testkit/dist/Selector.js' {
  declare module.exports: $Exports<'redux-testkit/dist/Selector'>;
}
declare module 'redux-testkit/dist/Thunk.js' {
  declare module.exports: $Exports<'redux-testkit/dist/Thunk'>;
}
declare module 'redux-testkit/dist/utils.js' {
  declare module.exports: $Exports<'redux-testkit/dist/utils'>;
}
declare module 'redux-testkit/src/FlushThunks.js' {
  declare module.exports: $Exports<'redux-testkit/src/FlushThunks'>;
}
declare module 'redux-testkit/src/index.js' {
  declare module.exports: $Exports<'redux-testkit/src/index'>;
}
declare module 'redux-testkit/src/Reducer.js' {
  declare module.exports: $Exports<'redux-testkit/src/Reducer'>;
}
declare module 'redux-testkit/src/Selector.js' {
  declare module.exports: $Exports<'redux-testkit/src/Selector'>;
}
declare module 'redux-testkit/src/Thunk.js' {
  declare module.exports: $Exports<'redux-testkit/src/Thunk'>;
}
declare module 'redux-testkit/src/utils.js' {
  declare module.exports: $Exports<'redux-testkit/src/utils'>;
}
declare module 'redux-testkit/wallaby.js' {
  declare module.exports: $Exports<'redux-testkit/wallaby'>;
}
