// flow-typed signature: 7ea868d51b5497ca9945a1ce9ea1761d
// flow-typed version: <<STUB>>/tape-run_v^5.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tape-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tape-run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tape-run/bin/run' {
  declare module.exports: any;
}

declare module 'tape-run/example/api' {
  declare module.exports: any;
}

declare module 'tape-run/test/api' {
  declare module.exports: any;
}

declare module 'tape-run/test/cli' {
  declare module.exports: any;
}

declare module 'tape-run/test/fixtures/error' {
  declare module.exports: any;
}

declare module 'tape-run/test/fixtures/fail' {
  declare module.exports: any;
}

declare module 'tape-run/test/fixtures/one' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tape-run/bin/run.js' {
  declare module.exports: $Exports<'tape-run/bin/run'>;
}
declare module 'tape-run/example/api.js' {
  declare module.exports: $Exports<'tape-run/example/api'>;
}
declare module 'tape-run/index' {
  declare module.exports: $Exports<'tape-run'>;
}
declare module 'tape-run/index.js' {
  declare module.exports: $Exports<'tape-run'>;
}
declare module 'tape-run/test/api.js' {
  declare module.exports: $Exports<'tape-run/test/api'>;
}
declare module 'tape-run/test/cli.js' {
  declare module.exports: $Exports<'tape-run/test/cli'>;
}
declare module 'tape-run/test/fixtures/error.js' {
  declare module.exports: $Exports<'tape-run/test/fixtures/error'>;
}
declare module 'tape-run/test/fixtures/fail.js' {
  declare module.exports: $Exports<'tape-run/test/fixtures/fail'>;
}
declare module 'tape-run/test/fixtures/one.js' {
  declare module.exports: $Exports<'tape-run/test/fixtures/one'>;
}
