// flow-typed signature: 61f2b0499c405e469468197600158dc6
// flow-typed version: <<STUB>>/testcafe_v^15.1.3/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe/_compiled_/control_panel/ace/ace' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/ext-language_tools' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/ext-static_highlight' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/mode-html' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/mode-javascript' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/snippets/html' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/snippets/javascript' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/snippets/json' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/snippets/text' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/theme-textmate' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/ace/worker-javascript' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/control_panel' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/dx/dx.webappjs' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/control_panel/dx/globalize.min' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/hammerhead_client/hammerhead' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/ace' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/ext-language_tools' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/ext-static_highlight' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/mode-html' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/mode-javascript' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/snippets/html' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/snippets/javascript' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/snippets/json' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/snippets/text' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/theme-textmate' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/ace/worker-javascript' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/dx/dx.webappjs' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/dx/globalize.min' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/init' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/actions/action' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/actions/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/app' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/context-menu-item/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/context-menu/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/data-driven-test/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/dir-item/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/empty-item-view/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/file-item/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/fs-node/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/fs-tree-view/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/header/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/item-view/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/left-panel/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/main-menu/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/right-panel/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/split-view/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/step-view/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/tab-item/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/tabs-view/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/tabs/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/test-item/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/test-view/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/title-bar/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/toolbar-btn/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/toolbar-separator/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/toolbar/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/window-btns/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/components/work-space/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/dispatcher/index' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/stores/tabs-view-actions' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/stores/tabs-view-store' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/stores/tree-view-actions' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/js/stores/tree-view-store' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/studio/react' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/testcafe_client/testcafe_core' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/testcafe_client/testcafe_recorder' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/testcafe_client/testcafe_ui_core' {
  declare module.exports: any;
}

declare module 'testcafe/_compiled_/testcafe_client/testcafe_ui_recorder' {
  declare module.exports: any;
}

declare module 'testcafe/control_panel/index' {
  declare module.exports: any;
}

declare module 'testcafe/control_panel/lib/const' {
  declare module.exports: any;
}

declare module 'testcafe/control_panel/lib/errors' {
  declare module.exports: any;
}

declare module 'testcafe/control_panel/lib/server' {
  declare module.exports: any;
}

declare module 'testcafe/examples/example.test' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/index' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/charset' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/content-length' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/cookie_shelf' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/events' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/form_data' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/header-transforms' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/injector' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/processed_js_cache' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/proxy' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/server_errs' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/server' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/service_channel' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/lib/url_util' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/shared/client_errs' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/shared/const' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/shared/js_parsing_tools' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/shared/js_processor' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/shared/page_processor' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/shared/service_msg_cmd' {
  declare module.exports: any;
}

declare module 'testcafe/hammerhead/shared/url_util' {
  declare module.exports: any;
}

declare module 'testcafe/lib/cli/cli' {
  declare module.exports: any;
}

declare module 'testcafe/lib/cli/help' {
  declare module.exports: any;
}

declare module 'testcafe/lib/cli/index' {
  declare module.exports: any;
}

declare module 'testcafe/lib/config/index' {
  declare module.exports: any;
}

declare module 'testcafe/lib/config/installed_browsers' {
  declare module.exports: any;
}

declare module 'testcafe/lib/config/tcp_ports' {
  declare module.exports: any;
}

declare module 'testcafe/lib/config/validator' {
  declare module.exports: any;
}

declare module 'testcafe/lib/err_msg_builder/index' {
  declare module.exports: any;
}

declare module 'testcafe/lib/err_msg_builder/markdown_formatter' {
  declare module.exports: any;
}

declare module 'testcafe/lib/err_msg_builder/plain_text_formatter' {
  declare module.exports: any;
}

declare module 'testcafe/lib/err_msg_builder/util' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/analysis/call_analyzer' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/analysis/require_analyzer' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/analysis/steps_analyzer' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/ast' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/code_generator' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/common' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/compiler' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/err_codes' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fixture_code/index' {
  declare module.exports: any;
}

declare module 'testcafe/lib/fs_util' {
  declare module.exports: any;
}

declare module 'testcafe/lib/server/api' {
  declare module.exports: any;
}

declare module 'testcafe/lib/server/assets_manager' {
  declare module.exports: any;
}

declare module 'testcafe/lib/server/const' {
  declare module.exports: any;
}

declare module 'testcafe/lib/server/recorder' {
  declare module.exports: any;
}

declare module 'testcafe/lib/server/server_errs' {
  declare module.exports: any;
}

declare module 'testcafe/lib/server/test_cafe' {
  declare module.exports: any;
}

declare module 'testcafe/lib/server/uxlog' {
  declare module.exports: any;
}

declare module 'testcafe/lib/shared/client_errs' {
  declare module.exports: any;
}

declare module 'testcafe/lib/shared/const' {
  declare module.exports: any;
}

declare module 'testcafe/lib/shared/service_msg_cmd' {
  declare module.exports: any;
}

declare module 'testcafe/lib/test_runner/index' {
  declare module.exports: any;
}

declare module 'testcafe/lib/test_runner/reporter' {
  declare module.exports: any;
}

declare module 'testcafe/lib/test_runner/worker_pool' {
  declare module.exports: any;
}

declare module 'testcafe/lib/upload' {
  declare module.exports: any;
}

declare module 'testcafe/lib/vfs/index' {
  declare module.exports: any;
}

declare module 'testcafe/lib/vfs/status_indication' {
  declare module.exports: any;
}

declare module 'testcafe/lib/vfs/test_suite_factory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe/_compiled_/control_panel/ace/ace.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/ace'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/ext-language_tools.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/ext-language_tools'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/ext-static_highlight.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/ext-static_highlight'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/mode-html.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/mode-html'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/mode-javascript.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/mode-javascript'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/snippets/html.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/snippets/html'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/snippets/javascript.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/snippets/javascript'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/snippets/json.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/snippets/json'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/snippets/text.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/snippets/text'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/theme-textmate.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/theme-textmate'>;
}
declare module 'testcafe/_compiled_/control_panel/ace/worker-javascript.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/ace/worker-javascript'>;
}
declare module 'testcafe/_compiled_/control_panel/control_panel.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/control_panel'>;
}
declare module 'testcafe/_compiled_/control_panel/dx/dx.webappjs.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/dx/dx.webappjs'>;
}
declare module 'testcafe/_compiled_/control_panel/dx/globalize.min.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/control_panel/dx/globalize.min'>;
}
declare module 'testcafe/_compiled_/hammerhead_client/hammerhead.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/hammerhead_client/hammerhead'>;
}
declare module 'testcafe/_compiled_/studio/ace/ace.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/ace'>;
}
declare module 'testcafe/_compiled_/studio/ace/ext-language_tools.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/ext-language_tools'>;
}
declare module 'testcafe/_compiled_/studio/ace/ext-static_highlight.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/ext-static_highlight'>;
}
declare module 'testcafe/_compiled_/studio/ace/mode-html.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/mode-html'>;
}
declare module 'testcafe/_compiled_/studio/ace/mode-javascript.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/mode-javascript'>;
}
declare module 'testcafe/_compiled_/studio/ace/snippets/html.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/snippets/html'>;
}
declare module 'testcafe/_compiled_/studio/ace/snippets/javascript.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/snippets/javascript'>;
}
declare module 'testcafe/_compiled_/studio/ace/snippets/json.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/snippets/json'>;
}
declare module 'testcafe/_compiled_/studio/ace/snippets/text.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/snippets/text'>;
}
declare module 'testcafe/_compiled_/studio/ace/theme-textmate.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/theme-textmate'>;
}
declare module 'testcafe/_compiled_/studio/ace/worker-javascript.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/ace/worker-javascript'>;
}
declare module 'testcafe/_compiled_/studio/dx/dx.webappjs.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/dx/dx.webappjs'>;
}
declare module 'testcafe/_compiled_/studio/dx/globalize.min.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/dx/globalize.min'>;
}
declare module 'testcafe/_compiled_/studio/init.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/init'>;
}
declare module 'testcafe/_compiled_/studio/js/actions/action.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/actions/action'>;
}
declare module 'testcafe/_compiled_/studio/js/actions/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/actions/index'>;
}
declare module 'testcafe/_compiled_/studio/js/app.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/app'>;
}
declare module 'testcafe/_compiled_/studio/js/components/context-menu-item/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/context-menu-item/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/context-menu/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/context-menu/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/data-driven-test/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/data-driven-test/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/dir-item/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/dir-item/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/empty-item-view/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/empty-item-view/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/file-item/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/file-item/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/fs-node/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/fs-node/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/fs-tree-view/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/fs-tree-view/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/header/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/header/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/item-view/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/item-view/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/left-panel/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/left-panel/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/main-menu/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/main-menu/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/right-panel/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/right-panel/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/split-view/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/split-view/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/step-view/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/step-view/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/tab-item/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/tab-item/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/tabs-view/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/tabs-view/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/tabs/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/tabs/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/test-item/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/test-item/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/test-view/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/test-view/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/title-bar/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/title-bar/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/toolbar-btn/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/toolbar-btn/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/toolbar-separator/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/toolbar-separator/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/toolbar/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/toolbar/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/window-btns/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/window-btns/index'>;
}
declare module 'testcafe/_compiled_/studio/js/components/work-space/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/components/work-space/index'>;
}
declare module 'testcafe/_compiled_/studio/js/dispatcher/index.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/dispatcher/index'>;
}
declare module 'testcafe/_compiled_/studio/js/stores/tabs-view-actions.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/stores/tabs-view-actions'>;
}
declare module 'testcafe/_compiled_/studio/js/stores/tabs-view-store.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/stores/tabs-view-store'>;
}
declare module 'testcafe/_compiled_/studio/js/stores/tree-view-actions.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/stores/tree-view-actions'>;
}
declare module 'testcafe/_compiled_/studio/js/stores/tree-view-store.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/js/stores/tree-view-store'>;
}
declare module 'testcafe/_compiled_/studio/react.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/studio/react'>;
}
declare module 'testcafe/_compiled_/testcafe_client/testcafe_core.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/testcafe_client/testcafe_core'>;
}
declare module 'testcafe/_compiled_/testcafe_client/testcafe_recorder.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/testcafe_client/testcafe_recorder'>;
}
declare module 'testcafe/_compiled_/testcafe_client/testcafe_ui_core.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/testcafe_client/testcafe_ui_core'>;
}
declare module 'testcafe/_compiled_/testcafe_client/testcafe_ui_recorder.js' {
  declare module.exports: $Exports<'testcafe/_compiled_/testcafe_client/testcafe_ui_recorder'>;
}
declare module 'testcafe/control_panel/index.js' {
  declare module.exports: $Exports<'testcafe/control_panel/index'>;
}
declare module 'testcafe/control_panel/lib/const.js' {
  declare module.exports: $Exports<'testcafe/control_panel/lib/const'>;
}
declare module 'testcafe/control_panel/lib/errors.js' {
  declare module.exports: $Exports<'testcafe/control_panel/lib/errors'>;
}
declare module 'testcafe/control_panel/lib/server.js' {
  declare module.exports: $Exports<'testcafe/control_panel/lib/server'>;
}
declare module 'testcafe/examples/example.test.js' {
  declare module.exports: $Exports<'testcafe/examples/example.test'>;
}
declare module 'testcafe/hammerhead/index.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/index'>;
}
declare module 'testcafe/hammerhead/lib/charset.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/charset'>;
}
declare module 'testcafe/hammerhead/lib/content-length.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/content-length'>;
}
declare module 'testcafe/hammerhead/lib/cookie_shelf.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/cookie_shelf'>;
}
declare module 'testcafe/hammerhead/lib/events.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/events'>;
}
declare module 'testcafe/hammerhead/lib/form_data.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/form_data'>;
}
declare module 'testcafe/hammerhead/lib/header-transforms.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/header-transforms'>;
}
declare module 'testcafe/hammerhead/lib/injector.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/injector'>;
}
declare module 'testcafe/hammerhead/lib/processed_js_cache.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/processed_js_cache'>;
}
declare module 'testcafe/hammerhead/lib/proxy.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/proxy'>;
}
declare module 'testcafe/hammerhead/lib/server_errs.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/server_errs'>;
}
declare module 'testcafe/hammerhead/lib/server.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/server'>;
}
declare module 'testcafe/hammerhead/lib/service_channel.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/service_channel'>;
}
declare module 'testcafe/hammerhead/lib/url_util.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/lib/url_util'>;
}
declare module 'testcafe/hammerhead/shared/client_errs.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/shared/client_errs'>;
}
declare module 'testcafe/hammerhead/shared/const.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/shared/const'>;
}
declare module 'testcafe/hammerhead/shared/js_parsing_tools.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/shared/js_parsing_tools'>;
}
declare module 'testcafe/hammerhead/shared/js_processor.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/shared/js_processor'>;
}
declare module 'testcafe/hammerhead/shared/page_processor.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/shared/page_processor'>;
}
declare module 'testcafe/hammerhead/shared/service_msg_cmd.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/shared/service_msg_cmd'>;
}
declare module 'testcafe/hammerhead/shared/url_util.js' {
  declare module.exports: $Exports<'testcafe/hammerhead/shared/url_util'>;
}
declare module 'testcafe/index' {
  declare module.exports: $Exports<'testcafe'>;
}
declare module 'testcafe/index.js' {
  declare module.exports: $Exports<'testcafe'>;
}
declare module 'testcafe/lib/cli/cli.js' {
  declare module.exports: $Exports<'testcafe/lib/cli/cli'>;
}
declare module 'testcafe/lib/cli/help.js' {
  declare module.exports: $Exports<'testcafe/lib/cli/help'>;
}
declare module 'testcafe/lib/cli/index.js' {
  declare module.exports: $Exports<'testcafe/lib/cli/index'>;
}
declare module 'testcafe/lib/config/index.js' {
  declare module.exports: $Exports<'testcafe/lib/config/index'>;
}
declare module 'testcafe/lib/config/installed_browsers.js' {
  declare module.exports: $Exports<'testcafe/lib/config/installed_browsers'>;
}
declare module 'testcafe/lib/config/tcp_ports.js' {
  declare module.exports: $Exports<'testcafe/lib/config/tcp_ports'>;
}
declare module 'testcafe/lib/config/validator.js' {
  declare module.exports: $Exports<'testcafe/lib/config/validator'>;
}
declare module 'testcafe/lib/err_msg_builder/index.js' {
  declare module.exports: $Exports<'testcafe/lib/err_msg_builder/index'>;
}
declare module 'testcafe/lib/err_msg_builder/markdown_formatter.js' {
  declare module.exports: $Exports<'testcafe/lib/err_msg_builder/markdown_formatter'>;
}
declare module 'testcafe/lib/err_msg_builder/plain_text_formatter.js' {
  declare module.exports: $Exports<'testcafe/lib/err_msg_builder/plain_text_formatter'>;
}
declare module 'testcafe/lib/err_msg_builder/util.js' {
  declare module.exports: $Exports<'testcafe/lib/err_msg_builder/util'>;
}
declare module 'testcafe/lib/fixture_code/analysis/call_analyzer.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/analysis/call_analyzer'>;
}
declare module 'testcafe/lib/fixture_code/analysis/require_analyzer.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/analysis/require_analyzer'>;
}
declare module 'testcafe/lib/fixture_code/analysis/steps_analyzer.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/analysis/steps_analyzer'>;
}
declare module 'testcafe/lib/fixture_code/ast.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/ast'>;
}
declare module 'testcafe/lib/fixture_code/code_generator.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/code_generator'>;
}
declare module 'testcafe/lib/fixture_code/common.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/common'>;
}
declare module 'testcafe/lib/fixture_code/compiler.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/compiler'>;
}
declare module 'testcafe/lib/fixture_code/err_codes.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/err_codes'>;
}
declare module 'testcafe/lib/fixture_code/index.js' {
  declare module.exports: $Exports<'testcafe/lib/fixture_code/index'>;
}
declare module 'testcafe/lib/fs_util.js' {
  declare module.exports: $Exports<'testcafe/lib/fs_util'>;
}
declare module 'testcafe/lib/server/api.js' {
  declare module.exports: $Exports<'testcafe/lib/server/api'>;
}
declare module 'testcafe/lib/server/assets_manager.js' {
  declare module.exports: $Exports<'testcafe/lib/server/assets_manager'>;
}
declare module 'testcafe/lib/server/const.js' {
  declare module.exports: $Exports<'testcafe/lib/server/const'>;
}
declare module 'testcafe/lib/server/recorder.js' {
  declare module.exports: $Exports<'testcafe/lib/server/recorder'>;
}
declare module 'testcafe/lib/server/server_errs.js' {
  declare module.exports: $Exports<'testcafe/lib/server/server_errs'>;
}
declare module 'testcafe/lib/server/test_cafe.js' {
  declare module.exports: $Exports<'testcafe/lib/server/test_cafe'>;
}
declare module 'testcafe/lib/server/uxlog.js' {
  declare module.exports: $Exports<'testcafe/lib/server/uxlog'>;
}
declare module 'testcafe/lib/shared/client_errs.js' {
  declare module.exports: $Exports<'testcafe/lib/shared/client_errs'>;
}
declare module 'testcafe/lib/shared/const.js' {
  declare module.exports: $Exports<'testcafe/lib/shared/const'>;
}
declare module 'testcafe/lib/shared/service_msg_cmd.js' {
  declare module.exports: $Exports<'testcafe/lib/shared/service_msg_cmd'>;
}
declare module 'testcafe/lib/test_runner/index.js' {
  declare module.exports: $Exports<'testcafe/lib/test_runner/index'>;
}
declare module 'testcafe/lib/test_runner/reporter.js' {
  declare module.exports: $Exports<'testcafe/lib/test_runner/reporter'>;
}
declare module 'testcafe/lib/test_runner/worker_pool.js' {
  declare module.exports: $Exports<'testcafe/lib/test_runner/worker_pool'>;
}
declare module 'testcafe/lib/upload.js' {
  declare module.exports: $Exports<'testcafe/lib/upload'>;
}
declare module 'testcafe/lib/vfs/index.js' {
  declare module.exports: $Exports<'testcafe/lib/vfs/index'>;
}
declare module 'testcafe/lib/vfs/status_indication.js' {
  declare module.exports: $Exports<'testcafe/lib/vfs/status_indication'>;
}
declare module 'testcafe/lib/vfs/test_suite_factory.js' {
  declare module.exports: $Exports<'testcafe/lib/vfs/test_suite_factory'>;
}
