// flow-typed signature: 9651d464e0932745be1dd35229176335
// flow-typed version: <<STUB>>/webpack-tape-run_v^0.0.7/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-tape-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-tape-run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-tape-run/test' {
  declare module.exports: any;
}

declare module 'webpack-tape-run/webpack.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-tape-run/index' {
  declare module.exports: $Exports<'webpack-tape-run'>;
}
declare module 'webpack-tape-run/index.js' {
  declare module.exports: $Exports<'webpack-tape-run'>;
}
declare module 'webpack-tape-run/test.js' {
  declare module.exports: $Exports<'webpack-tape-run/test'>;
}
declare module 'webpack-tape-run/webpack.test.js' {
  declare module.exports: $Exports<'webpack-tape-run/webpack.test'>;
}
