# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moves', '0016_auto_20181223_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recent_move_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.MoveList')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
