# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0016_auto_20181223_0935'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileToMoveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField()),
                ('move_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.MoveList')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='recent_move_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='moves.MoveList'),
        ),
        migrations.AddField(
            model_name='profiletomovelist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='move_lists',
            field=models.ManyToManyField(through='app.ProfileToMoveList', to='moves.MoveList'),
        ),
    ]
