# Generated by Django 2.1.7 on 2019-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='move',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
