# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
