# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 05:55
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def gen_slug(apps, schema_editor):
    MyModel = apps.get_model('moves', 'Move')  # noqa
    for row in MyModel.objects.all():
        row.slug = slugify(row.name)
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_add slug non-unique'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
