# Generated by Django 2.1.7 on 2019-03-26 17:40

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_auto_20190314_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_MovePrivateData_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'abstract': False,
                'ordering': ('name',),
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_moveprivatedata_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='moveprivatedata',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=10, space_delimiter=False, to='moves.Tagulous_MovePrivateData_tags'),
        ),
    ]
