# Generated by Django 2.1.7 on 2019-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0004_move_source_move_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelist',
            name='role',
            field=models.CharField(choices=[('', 'default'),
                                            ('drafts', 'drafts'),
                                            ('trash', 'trash')],
                                   default='',
                                   max_length=200),
        ),
    ]
