# Generated by Django 2.1.7 on 2019-04-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0005_movelist_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movelist',
            name='is_trash',
        ),
    ]
