# Generated by Django 2.1.7 on 2019-04-09 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0006_remove_movelist_is_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='variations',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=[],
                size=None),
        ),
    ]
