# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moves', '0007_auto_20180805_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tagulous_MoveList_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterField(
            model_name='move',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=10, space_delimiter=False, to='moves.Tagulous_Move_tags'),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_movelist_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='movelistitem',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.Move'),
        ),
        migrations.AddField(
            model_name='movelistitem',
            name='move_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.MoveList'),
        ),
        migrations.AddField(
            model_name='movelist',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=10, space_delimiter=False, to='moves.Tagulous_MoveList_tags'),
        ),
    ]
