# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 15:04
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0008_auto_20181214_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoveTip',
            new_name='Tip',
        ),
        migrations.RenameModel(
            old_name='MoveVideoLink',
            new_name='VideoLink',
        ),
        migrations.AlterField(
            model_name='movelist',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=10, space_delimiter=False, to='moves.Tagulous_MoveList_tags'),
        ),
    ]
