# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0010_auto_20181214_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelist',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
