# Generated by Django 2.1.7 on 2019-09-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0010_auto_20190914_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
