# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-16 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0011_movelist_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveprivatedata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moveprivatedata',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_datas', to='moves.Move'),
        ),
    ]
