# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0012_auto_20181216_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveList2Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.Move')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='movelist',
            name='moves',
        ),
        migrations.AddField(
            model_name='movelist2move',
            name='move_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.MoveList'),
        ),
        migrations.AddField(
            model_name='movelist',
            name='moves_ext',
            field=models.ManyToManyField(through='moves.MoveList2Move', to='moves.Move'),
        ),
    ]
