# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0013_auto_20181218_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movelist',
            old_name='moves_ext',
            new_name='moves',
        ),
    ]
