# Generated by Django 2.1.7 on 2019-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0013_auto_20190916_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='end_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='start_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
