# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0014_auto_20181218_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelist',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
