version : '2'

services :
  app:
    depends_on:
    - db
    image: linsci:base
    ports:
      - "8000:8000"
    # tty: True
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: app.settings.dev
    volumes_from:
    - container:dc_linsci_pip_packages
    - container:dc_linsci_node_modules
    volumes:
      # map the src directory to opt/app-root/src
      - ..:$SRV_DIR/src
      # Preserve the following directories written by the docker container
      # Note: first run `sudo python dev/configure.py` to create /srv/linsci
      - /srv/linsci/static:$SRV_DIR/static
      - /srv/linsci/dumps:$SRV_DIR/dumps
      - /srv/linsci/log:$SRV_DIR/log
      - /srv/linsci/.pytest_report:$SRV_DIR/.pytest_report
      - /srv/linsci/.ipython:$SRV_DIR/.ipython
      - /srv/linsci/.bashrc:$SRV_DIR/.bashrc
      - /srv/linsci/.config:$SRV_DIR/.config
    command: sleep 10000000
  db:
    image: linsci:base
    ports:
      - "5432:5432"
    volumes_from:
      - container:dc_linsci_pg
    command: sudo -u postgres /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf
