ROOT:
  src_dir: ${/ROOT/project_dir}/src
  shared_config_dir: ${/ROOT/src_dir}/extra/dodo_commands/res
  command_path:
  - ~/.dodo_commands/default_project/commands/*
  - ${/ROOT/src_dir}/extra/dodo_commands/dodo_linsci_commands
  version: 1.0.0

LAYERS:
  - ~/.dodo_commands/layers/*.yaml
  - django.dev.yaml
  - docker.yaml

LAYER_GROUPS:
  server:
  - react:
      inferred_by: [nps, node-install-packages, flow-install-types]
  - django:
      inferred_by: [django-manage, make, pip-install-packages]
  salt:
  - local: {}
  - server: {}
  deploy:
  - deploy:
      target_path: drops/dodo_deploy_commands/drop.on.yaml

MENU:
  commands:
    react-server:
    - dodo nps webpack.watch
    - dodo nps flow.watch
    - dodo nps test
    django-server:
    - dodo django.make runserver
    ssh:
    - dodo ssh-agent restart
    db:
    - dodo django-manage createsuperuser --email=mnieber@gmail.com --username=admin
    - dodo django-manage restore-db --list
    - dodo django-manage dump-db --print-pw
    - dodo django-manage makemigrations moves

