DJANGO:
  src_dir: ${/SERVER/src_dir}/website/django_wagtail
  python: ${/SERVER/venv_dir}/bin/python
  migrations_local_dir: ${/SERVER/install_dir}/migrations_local
  runserver_args:
  - --nostatic

DOCKER:
  home: /root
  containers:
    pg: dc_pandb
    migrations: dc_pandb_migrations
    static_data: dc_pan_static
    packages: dc_pan_packages
  options:
    '*':
      volumes_from_list:
      - ${/DOCKER/containers/static_data}
      - ${/DOCKER/containers/migrations}
      - ${/DOCKER/containers/packages}
      volume_map:
        ${/ROOT/src_dir}: ${/SERVER/src_dir}
      image: ${/DOCKER/images/base/image}
    bash:
      cwd: /srv/pan/src/salt
    django-manage:
      link_list:
      - pg
    django-runserver:
      link_list:
      - pg
      publish_list:
      - 8000
    run-postgres:
      name: pg
      volumes_from_list:
      - ${/DOCKER/containers/pg}

SSH_AGENT:
  key_names: [id_vegtech_rsa]
  docker_image: vegtech/ssh-agent

SSH:
  key_name: id_vegtech_rsa

SALT:
  docker_image: vegtech/salt
  src_dir: ${/ROOT/src_dir}
  top_dir: salt

PYTEST:
  pytest: ${/SERVER/venv_dir}/bin/pytest
  src_dir: ${/DJANGO/src_dir}

ROOT:
  src_dir: ${/ROOT/project_dir}/src
  layers:
  - ~/.dodo_commands/layers/*.yaml
  - docker_images.yaml
  - salt.local.yaml
  decorators:
    docker: [django-manage, django-runserver, docker, node-sass, pytest, webpack,
      update-salt-package, run-postgres, pan-dockerupdate, install-packages]
    pause: [django-runserver]
  command_path:
  - - ~/.dodo_commands
    - default_commands/*
  - - ${/ROOT/src_dir}/extra/dodo_commands
    - pan_commands
  version: 1.0.0

DIAGNOSE:
  src_dir: ${/ROOT/src_dir}/extra/dodo_commands/diagnose
  output_dir: ${/ROOT/project_dir}/res/diagnose
  filters:
  - - ${/DIAGNOSE/src_dir}
    - filters

TMUX:
  docker_kill: [django-runserver, node-sass, webpack]
  check_exists: /media/maarten/4de51826-182f-4043-b3bf-02d5eeb220e0
  commands:
  - dodo run-postgres
  - dodo django-runserver
  - dodo webpack --watch
  - dodo ssh-agent restart

SERVER:
  install_dir: /srv/pan
  src_dir: ${/SERVER/install_dir}/src
  node_modules_dir: ${/SERVER/src_dir}/website/node_modules
  venv_dir: ${/SERVER/install_dir}/env

WEBPACK:
  webpack: ${/SERVER/node_modules_dir}/.bin/webpack
  webpack_dir: ${/SERVER/src_dir}/website

