# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 10:43
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import moves.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('difficulty', enumfields.fields.EnumField(enum=moves.models.Difficulty, max_length=7)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', slotname='description', to='cms.Placeholder')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='MoveVideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('nr_votes', models.IntegerField(default=0, editable=False)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='moves.Move')),
            ],
            options={
                'verbose_name': 'Video Link',
                'verbose_name_plural': 'Video Links',
            },
        ),
    ]
