# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovePrivateNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.Move')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
