# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movevideolink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
