# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoLink',
            new_name='MoveVideoLink',
        ),
    ]
