# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_move_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='moves.Move')),
            ],
        ),
    ]
