# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_auto_20180627_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='name',
            field=models.CharField(default='basic', max_length=200),
            preserve_default=False,
        ),
    ]
