# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 07:59
from __future__ import unicode_literals

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moves', '0002_moveprivatenotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovePrivateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.Move')),
                ('notes', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', slotname='notes', to='cms.Placeholder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='moveprivatenotes',
            name='move',
        ),
        migrations.RemoveField(
            model_name='moveprivatenotes',
            name='owner',
        ),
        migrations.DeleteModel(
            name='MovePrivateNotes',
        ),
    ]
