# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_movevideolink_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movevideolink',
            name='nr_votes',
        ),
    ]
