# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0003_move_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movevideolink',
            options={'verbose_name': 'Video Link', 'verbose_name_plural': 'Video Links'},
        ),
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='movevideolink',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='moves.Move'),
        ),
    ]
