# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 08:51
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('moves', '0004_auto_20180627_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='moves', to='cms.Placeholder')),
            ],
        ),
    ]
