# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 04:19
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0004_auto_20180721_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveprivatedata',
            name='notes',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', slotname='Private notes', to='cms.Placeholder'),
        ),
    ]
