# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0005_movespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movespage',
            name='name',
            field=models.CharField(default='Moves', max_length=255),
            preserve_default=False,
        ),
    ]
