# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 10:02
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('moves', '0006_movespage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='foo',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foo', slotname='foo', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='move',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', slotname='description', to='cms.Placeholder'),
        ),
    ]
