// flow-typed signature: 5e6f1f0ee4ddba93f57c414ed26271f8
// flow-typed version: <<STUB>>/cheeseburger-menu_v^0.0.13/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cheeseburger-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cheeseburger-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cheeseburger-menu/dist' {
  declare module.exports: any;
}

declare module 'cheeseburger-menu/src' {
  declare module.exports: any;
}

declare module 'cheeseburger-menu/src/styles' {
  declare module.exports: any;
}

declare module 'cheeseburger-menu/stories' {
  declare module.exports: any;
}

declare module 'cheeseburger-menu/stories/menu' {
  declare module.exports: any;
}

declare module 'cheeseburger-menu/test/test' {
  declare module.exports: any;
}

declare module 'cheeseburger-menu/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cheeseburger-menu/dist/index' {
  declare module.exports: $Exports<'cheeseburger-menu/dist'>;
}
declare module 'cheeseburger-menu/dist/index.js' {
  declare module.exports: $Exports<'cheeseburger-menu/dist'>;
}
declare module 'cheeseburger-menu/index' {
  declare module.exports: $Exports<'cheeseburger-menu'>;
}
declare module 'cheeseburger-menu/index.js' {
  declare module.exports: $Exports<'cheeseburger-menu'>;
}
declare module 'cheeseburger-menu/src/index' {
  declare module.exports: $Exports<'cheeseburger-menu/src'>;
}
declare module 'cheeseburger-menu/src/index.js' {
  declare module.exports: $Exports<'cheeseburger-menu/src'>;
}
declare module 'cheeseburger-menu/src/styles.js' {
  declare module.exports: $Exports<'cheeseburger-menu/src/styles'>;
}
declare module 'cheeseburger-menu/stories/index' {
  declare module.exports: $Exports<'cheeseburger-menu/stories'>;
}
declare module 'cheeseburger-menu/stories/index.js' {
  declare module.exports: $Exports<'cheeseburger-menu/stories'>;
}
declare module 'cheeseburger-menu/stories/menu.js' {
  declare module.exports: $Exports<'cheeseburger-menu/stories/menu'>;
}
declare module 'cheeseburger-menu/test/test.js' {
  declare module.exports: $Exports<'cheeseburger-menu/test/test'>;
}
declare module 'cheeseburger-menu/webpack.config.js' {
  declare module.exports: $Exports<'cheeseburger-menu/webpack.config'>;
}
