// flow-typed signature: 56310a2b783859a183beb294a2def982
// flow-typed version: <<STUB>>/draft-js-import-html_v^1.2.1/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-import-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-import-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-import-html/esm/__tests__/parseHTML-test' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/esm/__tests__/stateFromHTML-test' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/esm/main' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/esm/parseHTML' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/esm/stateFromHTML' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/__tests__/parseHTML-test' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/__tests__/stateFromHTML-test' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/main' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/parseHTML' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/stateFromHTML' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-import-html/esm/__tests__/parseHTML-test.js' {
  declare module.exports: $Exports<'draft-js-import-html/esm/__tests__/parseHTML-test'>;
}
declare module 'draft-js-import-html/esm/__tests__/stateFromHTML-test.js' {
  declare module.exports: $Exports<'draft-js-import-html/esm/__tests__/stateFromHTML-test'>;
}
declare module 'draft-js-import-html/esm/main.js' {
  declare module.exports: $Exports<'draft-js-import-html/esm/main'>;
}
declare module 'draft-js-import-html/esm/parseHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/esm/parseHTML'>;
}
declare module 'draft-js-import-html/esm/stateFromHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/esm/stateFromHTML'>;
}
declare module 'draft-js-import-html/lib/__tests__/parseHTML-test.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/__tests__/parseHTML-test'>;
}
declare module 'draft-js-import-html/lib/__tests__/stateFromHTML-test.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/__tests__/stateFromHTML-test'>;
}
declare module 'draft-js-import-html/lib/main.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/main'>;
}
declare module 'draft-js-import-html/lib/parseHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/parseHTML'>;
}
declare module 'draft-js-import-html/lib/stateFromHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/stateFromHTML'>;
}
