// flow-typed signature: 1c41c06ddf995cb5ea0e0d7d5f0a4bb4
// flow-typed version: <<STUB>>/path-to-regex_v^1.3.1/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-to-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-to-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'path-to-regex/test/01.path-to-regex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'path-to-regex/index' {
  declare module.exports: $Exports<'path-to-regex'>;
}
declare module 'path-to-regex/index.js' {
  declare module.exports: $Exports<'path-to-regex'>;
}
declare module 'path-to-regex/test/01.path-to-regex.js' {
  declare module.exports: $Exports<'path-to-regex/test/01.path-to-regex'>;
}
