// flow-typed signature: 18b6a8ae69612729c0dbfc1096a893e8
// flow-typed version: <<STUB>>/recase_v^1.0.4/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recase/recase' {
  declare module.exports: any;
}

declare module 'recase/tests/test-edges' {
  declare module.exports: any;
}

declare module 'recase/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recase/recase.js' {
  declare module.exports: $Exports<'recase/recase'>;
}
declare module 'recase/tests/test-edges.js' {
  declare module.exports: $Exports<'recase/tests/test-edges'>;
}
declare module 'recase/tests/test.js' {
  declare module.exports: $Exports<'recase/tests/test'>;
}
