# Generated by Django 2.1.7 on 2019-04-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0008_auto_20190410_1954"),
    ]

    operations = [
        migrations.RenameField(
            model_name="move", old_name="variationNames", new_name="variation_names",
        ),
    ]
