# Generated by Django 2.1.7 on 2019-09-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0012_auto_20190915_1906"),
    ]

    operations = [
        migrations.RemoveField(model_name="videolink", name="move",),
        migrations.RemoveField(model_name="videolink", name="owner",),
        migrations.RenameField(model_name="move", old_name="url", new_name="link",),
        migrations.DeleteModel(name="VideoLink",),
    ]
