# Generated by Django 2.1.7 on 2019-09-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0014_auto_20190918_0939"),
    ]

    operations = [
        migrations.RemoveField(model_name="move", name="variation_names",),
    ]
