# Generated by Django 2.0.6 on 2018-06-25 15:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_auto_20180622_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='movepage',
            name='video_links',
            field=wagtail.core.fields.StreamField([('video_link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('votes', wagtail.core.blocks.IntegerBlock(default=0))]))], default=[]),
        ),
    ]
