# Generated by Django 2.0.6 on 2018-06-26 07:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0004_auto_20180626_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movepage',
            name='video_links',
            field=wagtail.core.fields.StreamField([('video_link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('nr_votes', wagtail.core.blocks.IntegerBlock(default=0, editable=False))]))], default=[]),
        ),
    ]
