# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0003_fill slug field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
