# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def fill_move_uuid_field(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Move = apps.get_model('moves', 'Move')  # noqa
    for move in Move.objects.all():
        move.uuid = uuid.uuid4()
        move.save()

    MoveTip = apps.get_model('moves', 'MoveTip')  # noqa
    for moveTip in MoveTip.objects.all():
        moveTip.move_uuid = moveTip.move.uuid
        moveTip.save()

    MoveVideoLink = apps.get_model('moves', 'MoveVideoLink')  # noqa
    for moveVideoLink in MoveVideoLink.objects.all():
        moveVideoLink.move_uuid = moveVideoLink.move.uuid
        moveVideoLink.save()

    MovePrivateData = apps.get_model('moves', 'MovePrivateData')  # noqa
    for movePrivateData in MovePrivateData.objects.all():
        movePrivateData.move_uuid = movePrivateData.move.uuid
        movePrivateData.save()


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0004_make slug field unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='Move',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='MoveTip',
            name='move_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='MoveVideoLink',
            name='move_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='MovePrivateData',
            name='move_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_move_uuid_field),
        migrations.RemoveField('MoveTip', 'move'),
        migrations.RenameField(
            model_name='MoveTip', old_name='move_uuid', new_name='move_id'),
        migrations.RemoveField('MoveVideoLink', 'move'),
        migrations.RenameField(
            model_name='MoveVideoLink',
            old_name='move_uuid',
            new_name='move_id'),
        migrations.RemoveField('MovePrivateData', 'move'),
        migrations.RenameField(
            model_name='MovePrivateData',
            old_name='move_uuid',
            new_name='move_id'),
        migrations.RemoveField('Move', 'id'),
        migrations.RenameField(
            model_name='Move', old_name='uuid', new_name='id'),
        migrations.AlterField(
            model_name='Move',
            name='id',
            field=models.UUIDField(
                primary_key=True,
                default=uuid.uuid4,
                serialize=False,
                editable=False,
                unique=True),
        ),
    ]
